requirements.txt
setup.py

Adds a setup.py script so that users can either `pip install .` or do a `python setup.py install`

Add base setup.py

---

instapy/like_util.py

Just realized that if the user left the caption empty and after the
post date write an comment, it doesn't count as a caption. Fixed that
by getting the first comment from the post.
Also added a check if “PostPage” variable exists in “check_link”.

Check if the post/comment exists

---

instapy/print_log_writer.py

> Fixes the issue with crashing when the script is run with an entirely new account where there is no follower amount on the profile page

fixed problem with no follower count on completely new account

---

.gitignore
windows.ps1

Added Windows Install Script

---

instapy/clarifai_util.py
instapy/instapy.py
instapy/like_util.py

Going over the code, I saw some needless IFs which could be simplified into one liners.
Also, I cleaned up the code to use `any` function with a generator. `any` is pretty cool, especially when used in conjunction with a generator.

Simplify boolean logic

---

docs/_config.yml

Fixes #99 
Added title and description!

No title is set in the official page of InstaPy #99

---

instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/time_util.py
instapy/unfollow_util.py

Times that were fixed before now falls in a range +/- 50% from the original value selected from a normal distribution.
e.g. `sleep(2)` can now be anywhere in-between `sleep(1)` and `sleep(3)`, normally distributed in this range, centered around `2`.

Introduced random times to the script.

---

instapy/clarifai_util.py

No new features added, just a clean up.

Expand the tuple instead of accessing them by position

---

instapy/like_util.py

Fix ‘Page not Found’ issue.

---

README.md

Replaced all html tags with MarkDown equivalents.
Replaced apostrophes and quotation marks with typographic ones.

Replace html with markdown

---

README.md

When I first used this I had to read the source to figure out some details of the main methods:
- does tag = hashtag or is hashtag just a special kind of tag?
- can I omit '#'?
- are `like_by_tags` and `like_from_image` completely separate or do they work together? Is `like_from_image` some kind of starting point the bot starts looking for the tags specified in `like_by_tags`? (This question came up as there was just one comment for both methods and 'from' implies a starting point. Maybe should be called `like_by_tags_of_image`).
- why is the example url `www.instagram.com/image` not actually pointing to an image but a user? should I be passing an image or a user?
I tried to answer these questions in the README with an improved explanation.

improved like_from_image and like_by_tags documentation

---

instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py

Also, fixed issue where parenthesis were being printed together with the text.

Changed print style to newer `.format` one.

---

instapy/comment_util.py

Added unicode flag to string.format

Fixed comment_util emoji output

---

README.md
docs/index.md
instapy/instapy.py

I add an optional nogui parameter to the instapy class in order to use the project on a server without modifying the code.

Add nogui instapy constructor parameter

---

instapy/login_util.py

When the instagram website is in, for example, Brazillian Portuguese, there are errors because of the change of the name of certain html elements. So, this simple change fixes it.

Update login_util.py to avoid errors

---

README.md
docs/How_To_DO_Ubuntu.md
docs/How_to_Windows.md
docs/index.md

Added scripts as part of the How-To documentations for both Ubuntu and Windows.
Added links to How-To on README.md
Fixed license shield image broken link

Addressing #278

---

scripts/unix.sh
scripts/windows.ps1

I updated the scripts to be reflective of the "How-To"s. I will update the documentations in README.md, index.md, and their respective How-Tos shortly.

Updated both scripts

---

README.md
docs/index.md
instapy/comment_util.py
setup.py

PR addressing #143 raised by @raffg
This will let users type emojis in a text style such as --> :thumbs_up:

Emoji Code Names

---

instapy/views/image.py

Fix issue when perform like on an already liked.

Fix a typo on doing like when already liked.

---

instapy/instapy.py
instapy/views/image.py

Refers to comment_util fixes #288, please review.

Fix issue with invalid comment input element

---

README.md

A couple of comets back documentation was clean and understandable, but with the advent of new features it became very hard to read. For a new user it became difficult to find the main features instapy could provide.

Built a logical order in README

---

instapy/instapy.py

Hi this is the new feature like from last post where I made an issue about. Hope you enjoy it !

Like from last post

---

instapy/login_util.py

New class was added, this fixes it.

language selection fix

---

instapy/instapy.py

chromedriver binary path wasn't set the options, causing selenium to fail to find it.

Added to fix issue #338

---

instapy/instapy.py

Fix issues with self.aborting and small style fix.
[#398](https://github.com/timgrossmann/InstaPy/issues/398)

Fixed self.aborting issue. #398

---

README.md

Corrected some spelling errors and sentence structure in the readme file

modified: fixed some typos in the readme file

---

README.md
docs/How_to_Raspberry.md
examples/firefoxExample.py
instapy/instapy.py
instapy/login_util.py

**Firefox as an option for the user**
> Most of the operating systems distributions already include Firefox and geckodriver. Chrome and ChromeDriver might be an issue on some ARM based systems.
> 
> The idea here isn't to replace Chrome as default browser. Instead, my idea was to provide an option for the user while keeping Chrome as default since it indeed runs smoother.
>
> Following the Chrome setting, Firefox is also capable of disabling the image load to use less bandwidth.
**A way to disable language switch**
> The language switch function can switch to a random language on some systems that already defaults to English.
>
> A simple way to disable this function without having to dig into the code can help less experienced users
**The implicitly_wait always set to 25 might be too …

Firefox as an option and more "user-configurable" parameters 

---

README.md
examples/example.py
instapy/instapy.py
instapy/unfollow_util.py
instapy/util.py

**Follow the followers of a given user or follow everyone that a given user is following**
- Follows everyone or an specified amount of users
- Built-in delays following the ones we see in the unfollow function
- Keep track of followed users using the existing log handler
- Sets follow_restrict
- Skips users that are already being followed
- Sleeps for 10 minutes after 10 users
- Makes use of the dont_include list to skip users
**follow_through_dialog function**
- A centralized way to handle all the following tasks done in the dialog list
- Currently being used by both functions above
**formatNumber function**
- Converts to integer numbers like: 2.2K, 1K...
- Added to util.py
**Example for following followers**
- Examples were added

Follow someone else's followers

---

instapy/login_util.py

Fix language selector login issue

---

README.md
examples/example.py
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py

- All feature requested on #484
- Add like_by_user() function that like each given user's posts
- Include set_user_interact() to expand functionality with other feature
- change follow_user_followers return value to list of followed user for further interaction feature
**Single Use**
```python
#Likes 10 random photo of geach given user
session.like_by_user(usernames=['friend1', 'friend2', 'friend3'], amount=10, random=True, media='photo')
```
**Comined Use**
```python
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])
session.set_user_interact(amount=5, random=True) 
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, random=False, interact=True)
```

Like different pictures of a user's profile

---

instapy/like_util.py
instapy/login_util.py

The class name for "load more" is updated in like_util.py.
Also, I had to comment out 5 lines in login_util.py to as per issue #498 but there's probably a more elegant solution. 
Anyways, this version is up and running on my end.

Closes #502 pagination

---

README.md
examples/example.py
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py

Hi @timgrossmann , I've got some progress on this feature. So in a nutshell, I had to rewrite the **.like_by_feed** method completely so that it would be able to implement and call other methods which are necessary to meet the randomization, unfollow criteria and the filtering preferences based on comments and followers/likes restrictions. Currently, a new **.get_links_from_feed** method takes chunks of links present on the feed session and sends them to the **.like_by_feed** method, so that it visits each post's link individually in order to analyse its content - differently from the simple top-bottom approach that was in use before. The Clarifai Image checking is also being called by the **.like_by_feed** method, and if any sensitive content is found, the author gets immediately …

Improve the .like_by_feed feature #485

---

README.md
examples/example.py
instapy/instapy.py
instapy/unfollow_util.py

Solves issue #509
**Interact with the people that a given user is following
set_do_comment, set_do_follow and set_do_like are applicable**
```
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['natgeo'], amount=10, random=True)
```
**Interact with the people that is following a given user
set_do_comment, set_do_follow and set_do_like are applicable**
```
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70) …
```

Interact with the followers by liking & commenting without following

---

quickstart.py

I felt like we really needed an quickstart file that is not related to docker.
If you feel like it is not useful please reconsider that someone else myght have the sabe problem as myself had once couldnt not use the bott क्योंकि it does not contain a regular quickstart i dont even know what docker means

Create quickstart.py not related to docker

---

README.md
examples/example.py
instapy/instapy.py
instapy/unfollow_util.py

**add feature requested on #530 by @paunocu69**
- Add` sleep_delay` parameter for custom user defined sleep duration
- Input value in second, default `sleep_delay=600`
- example and README updated

User customizable delays

---

instapy/unfollow_util.py

- Add simple algorithm to check if amount of user needed to follow is sufficient
- Expand the amount when `random=True` for better sampling distribution

Ensuring the script gets the amount needed to follow

---

instapy/unfollow_util.py

This may fix the potential issues with the script trying to click DOM elements that are obscured.

Replace instances of click() with send_keys

---

instapy/unfollow_util.py

I found issue when I'm using like by tag. For example:
`session.like_by_tags(['hashtag'], amount=1)`
The main problem was with "find_element_by_xpath", after my fix it starts work properly.

Fixed error with searching 'Follow' and 'Following' buttons

---

instapy/unfollow_util.py

I think I've solved the issue with the un-clickable Follow button by just trying to find it by text (as it yet was for follow_given_user).
I hope I've done right with the code since its my first step into Python.

follow_user and follow_given_user 	Click on button via js

---

instapy/unfollow_util.py

As issued on #606, fixed unfocusable elements when following other users' followers/following.

Fixed XPATH selectors for followers/following and dialog boxes

---

instapy/unfollow_util.py

Fix random variable reference in follow_through_dialog.

Fix random on follow through dialog

---

instapy/unfollow_util.py

Unfollow with onlyInstapyFollowed=True not working

Fixed #584

---

instapy/unfollow_util.py

Checks if visible. Forces visibility and click

FIX visibility #615 problem

---

README.md
instapy/instapy.py
instapy/unfollow_util.py

FIFO and LIFO unfollow realization based on **automatedFollowedPool**

FIFO and LIFO unfollow

---

docker-compose.yml
docker-prod.yml

Setup docker volume for logs directory

---

instapy/unfollow_util.py

Fix "follow user's followers" when they have none

---

README.md
instapy/instapy.py
instapy/like_util.py

Optional parameter added to `like_by_locations` and `like_by_tags` to skip top posts section

Skip top posts

---

instapy/instapy.py
instapy/unfollow_util.py

#751 is occurring because InstaPy tries to click at "followers" link in private profiles, and in private profiles this link doesn't exist.
Code styled the method interact_user_followers in flake8
Removed unused variables inside interact_user_followers method

fix #751 bug, flake8 code style at interact_user_followers method

---

README.md
instapy/instapy.py

1. flake8 code style
2. deleted unused variables
3. deleted interact_by_users method that is obsolete and its not in the docs anymore (can we delete it?)

flake8 code style instapy.py

---

README.md
instapy/instapy.py
instapy/util.py

Prevents unfollow followers who have liked one of your latest x posts
session.set_unfollow_active_users(enable=False, posts=5)

set_unfollow_active_users

---

instapy/instapy.py

I put the try/except inside the 'for username in usernames' loops allowing for the use of the continue statement to go to the next username in the list when an Runtime error is caught.

Fix issue #774: follow_user_following

---

README.md

README reorganize

---

instapy/unfollow_util.py

The script is sleeping after every unfollow because of a simple typo in line 163.

Sleeping after every unfollow

---

instapy/comment_util.py

bug fix 817, opens comment section and refreshes comment element

---

instapy/unfollow_util.py

Is this logic needed ? Removing it, we fix the #779 bug. Random (True/False) continue working.

follow_user_followers not respecting amount to follow

---

instapy/comment_util.py
instapy/like_util.py
instapy/login_util.py
instapy/unfollow_util.py
instapy/util.py

I tried to make as simple as possible:
every server call is recorded at logs/activity.csv file, page load, page content, likes, comments, follows and unfollows are recorded by day in this file.
the file layout is:
```
date,likes,comments,follows,unfollows,server_calls
11/01/17,18,14,52,0,84
11/02/17,14,10,32,0,156
```
more informations about this feature: #839 
if you guys wanna keep activity.csv open to analyse it, this frankstein can help:
```python
from subprocess import call
from time import sleep
while(True):
with open('activity.csv') as f:
for line in f:
print line
sleep(0.2)
if 'str' in line:
break
else:
call(['clear'])

Record activity, generate statistics

---

instapy/like_util.py

Leaving the "Load not found" commented, maybe we will need a dual mode in future to support both types of pages- with and without load buttons.

Fixing #724 based on solutions in the comments

---

README.md
instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py
instapy/util.py

- Had to create a new PR to fix the rebase problem.
- Now it's easier to merge/test it. 
- There isn't README update yet, because I want to check if it's everything ok first.
**How does it work ?**
Blacklist feature for the campaign called "comments_campaign". Every interaction with a user, is stored in a csv file (blacklist.csv). This file contains a header (a dictionary), and you can find informations just opening the csv file and locating what you need through the dictionary (ex. blacklist{'campaign'} will list all campaign, and you can easily filter it by campaign, actions and users.
The csv field names are **profile,campaign,action**, and an example of how it's stored is:
profile,campaign,action
user1,campaign_1,followed
user1,campaign_1,liked
user2,campaign_1,followed …

Blacklist feature

---

instapy/instapy.py
instapy/like_util.py

changes xpaths to locate elements, removes unnecessary sleeps, fixes load button problem for like_by_feed

#878 bug fix (like_by_feed)

---

instapy/unfollow_util.py

thanks @arjunmurali1993, #914 #898 bug fix

layout change for unfollow button (arjunmurali1993 fix)

---

instapy/instapy.py

replaced forgotten clarifai_id call

---

README.md
instapy/instapy.py

```python
session.set_smart_hashtags(['cycling', 'roadbike'], limit=3, sort='top', log_tags=True)
session.like_by_tags(amount=10, use_smart_hashtags=True)
```

Smart hashtags

---

instapy/clarifai_util.py
instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/print_log_writer.py
instapy/unfollow_util.py
instapy/util.py

removes all print statements and uses Logging python module to handle logging informations

Update logging system

---

instapy/instapy.py

- When not setting the upper follower count, the it was defaulted to 0, which is completely wrong.
- Moved around the imports and removed duplicated ones
(found while testing #936 )

fixed small logic issue with not setting upper follower count

---

README.md
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py

- we're using random as argument and parameter, changed every argument/parameter from random to randomize

random argument/parameter changes

---

instapy/util.py

is there a better approach for line 144 ?

set_dont_unfollow_active_users code improvement and #931 fix

---

docker_conf/all_in_one/Dockerfile

chrome needs the package lsb-release installed

Make Dockerfile buildable again

---

instapy/clarifai_util.py

Also, let's show why Clarifai does not "approve" the image.

changed old loggins calls to the new logging call

---

instapy/unfollow_util.py

This change should fix the dialog not found issue during Unfollow.

fix issue #1007

---

instapy/unfollow_util.py

Making sure to keep following whitelisted users.

fix issue #974

---

instapy/unfollow_util.py

* unfollow OnlyNotFollowMe feature bug fix
* added two sleeps to slow down the queries
fixes #1029

#1029 bug fix

---

README.md
instapy/instapy.py
instapy/login_util.py

* when suspicious account is detected, send security code to users email, and ask it in console.

#1074 bugfix (wrong login data/suspicious attempt)

---

README.md
instapy/instapy.py
instapy/login_util.py

* #1121 bugfix
* code organization improvement
* adds bypass_suspicious_attempt back
* adds better documentation
The flow is:
bypass_suspicious_attempt=True and login issue -> it will bypass it, using security code approach
bypass_suspicious_attempt=False and login issue -> wrong login data
bypass_suspicious_attempt=True and login OK -> will login using cookie and shows "Unable to locate email or phone button, maybe bypass_suspicious_login=True isn't needed anymore"
bypass_suspicious_attempt=False and login OK -> will login using cookie

#1123 bugfix

---

quickstart.py

Just found out that our memory leak issue is caused when:
1. start InstaPy
2. InstaPy generates some error/exception
3. self.end() method is not called in the process
4. chrome and xvfb keeps open, consuming resources (cpu / memory)

Memory leak fix

---

instapy/like_util.py
instapy/unfollow_util.py

Need testing in other platforms/environments

Error fixes when using headless firefox in raspberry pi

---

setup.py

Update clarifai version

---

examples/multi-account.py

I had no problems running from the same IP.
The code is still crude but works fine, I'll be working on it and accepting suggestions.

Added multi-account example #451

---

README.md
instapy/instapy.py

Modification of the function like_by_tags to make possible follow a user without liking the image.
#1096

Add follow_by_tags

---

README.md
instapy/comment_util.py

#1165 
I considered adding a flag whether to format a comment or not, as it is possible to have many comments without format. However, comments are fairly short and I think it wouldn't affect performance too much.

Personlizing comments with username

---

instapy/unfollow_util.py

Fixes 
```
ERROR - set_automated_followed_pool error [Errno 2] No such file or directory: './logs/username_followedPool.csv'
unable to get followers and following information
```

made sure that followed pool.csv will be created if not present

---

instapy/like_util.py
instapy/time_util.py
instapy/unfollow_util.py
instapy/util.py

Too many crashes due to not being able to click an element on screen.
See this issue that explains this in a bit more detail: https://github.com/timgrossmann/InstaPy/issues/1232
I created a new function in `util.py` that clicks elements using a various number of techniques, see code for more info.
I've documented the code I changed pretty well, if you don't understand why I changed something, ask.

Abstracted out clicking elements

---

instapy/instapy.py

Ability to track users action in log if there is multi users using same script.

Added username to log

---

instapy/login_util.py

Instagram added another option that make script fail when start.

Change from 10 in the langunage bar to 11

---

instapy/instapy.py

self.logger referenced before it's created.

---

instapy/login_util.py

#1321 #1314 #1304 #1300 #1299 #1285 #1065 #1046 #1042 bug fix

1321_1314_1304_1300_1299_1285_1065_1046_1042_bug_fix

---

instapy/__init__.py
instapy/instapy.py
instapy/print_log_writer.py
instapy/settings.py
instapy/util.py
quickstart.py

I added global variables to instapy.py and a return statement to print_log_writer.py so that the number of followers, liked images, followed users, unfollowed users, already liked images, inappropriate images and commented images can be stored in the InstaPy-object and read from quickstart.py.
This also refers to: timgrossmann#1342

Added global variables

---

docs/How_to_Raspberry.md

This updates the Raspberry Pi documentation to use chrome (as noted in #1357). I have also created some ansible playbooks [here](https://github.com/Marto32/ansible-raspi-playbooks) to make this process much easier. LMK if there is interest and I can port them into this repo along with alternate setup instructions.

Update RPi Docs

---

README.md
instapy/instapy.py

Added 'comment_by_locations' method to allow commenting by locations without liking the posts. Just commenting. Because I needed that and wanted to return something to the community and others who might need the same :)

Added 'comment_by_locations' method to allow commenting by locations without likes

---

instapy/unfollow_util.py

Quick fix when something like this happens.
Only to some accounts, like mine.
When it happens it skips to the next step.

fix unfollow users that are following you

---

instapy/instapy.py
instapy/like_util.py
instapy/print_log_writer.py

Good when we handle real users and facing any bug so we can't unfollow anymore since the pool is empty.

Add utf-8 to reason not liked;Avoid divide by zero;Add missing functions: Capture all followed and unfollowed ever

---

instapy/instapy.py

TypeError: not all arguments converted during string formatting
https://github.com/timgrossmann/InstaPy/issues/1108

Fix string formatting

---

README.md

[Windows Task Scheduler](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383614(v=vs.85).aspx) is a simple program that all Windows users have, that allows InstaPy to be automated without installing any additional software. I have edited the readme to include instructions on how to setup InstaPy for Task Scheduler.
If style changes are requested, just let me know.

Automating InstaPy with Windows Task Scheduler

---

instapy/login_util.py

If the cookie associated with a login becomes "bad" for any reason, InstaPy previously did not have the ability to catch this. The most common reason for a cookie failing to work, is the user changing their password. 
login_util.py will check if a cookie is present, and if so, load it. With these changes, InstaPy will ensure the user is successfully logged in by checking if when loading www.instagram.com the user still sees a "Log in" button. If so, the cookie is assumed to be "bad" and re-created.
There are three states, and three associated test cases. These are listed below, and all three have passed successfully
1. Naive user  - no cookie has been created for this account
2. "Good" cookie - user has been successfully logged in on the active machine in the past, and loading the …

Fixed "bad" cookie

---

.gitignore
instapy/unfollow_util.py
instapy/util.py
tests/test_util.py

There is a bug that when the count does not end with a decimal e.g. 123k instead of 12.3k, the conversion is incorrectly done with dropping a zero.
Refactored the name to pep8.
Optimized imports.
Added test.

Refactored formatNumber and fixed decimal bug

---

.gitignore
instapy/instapy.py
tests/test_instapy.py

Added variable to prevent undefined error

---

instapy/instapy.py

With this settings:
```
session.set_do_follow(True, percentage=50)
session.set_do_like(True, percentage=75)
session.interact_by_users(list_of_500_usernames, amount=4, randomize=True)
```
Because of we decide if we should follow user while see each image - really count of follow will be more than 50%!.
But with this change of code we will decide if we should follow user only one time for one user.

interact_by_users: We should only once decide if we will follow user (rather than when viewing each of image)

---

README.md
instapy/instapy.py
proxy_extension.py

Usage:
```
from instapy import InstaPy 
from proxy_extension import create_proxy_extension
insta_username = ''
insta_password = ''
proxy = 'login:password@123.123.123.123:8000'
proxy_chrome_extension = create_proxy_extension(proxy)
session = InstaPy(
username=insta_username,
password=insta_password,
proxy_chrome_extension=proxy_chrome_extension,
headless_browser=False,
multi_logs=True,
)
```

Support proxy with authentication

---

instapy/unfollow_util.py

fixed to use 
user_data = json.loads(pre)['graphql']['user']

Additional fix for the Instagram web API change

---

instapy/like_util.py

First check if there is a like or unlike button via existing spans, next find the like button if it exists, which is much faster.

faster like button search for image liking

---

instapy/instapy.py
tests/test_instapy.py

Corrected like_img value

---

instapy/unfollow_util.py
tests/test_unfollow_util.py

Fixes #1597 
Cleaned up the function.
PS: how do I get rid of the merge branch on my master? I'm doing `git pull upstream master`? Those commits are unnecessary to show

Fixes local variable 'allfollowing' referenced before assignment

---

instapy/instapy.py

Support headless and UI proxy for chrome based on selenium proxy class (no extension needed)

Use chrome proxy without extention

---

instapy/like_util.py
tests/test_like_util.py

Fixes #1640 
@timgrossmann how long are you planning to support python2?

Added encoding to inappropriate message

---

instapy/instapy.py
tests/test_unfollow_util.py

I've noticed that the logfolder are created in the root incorrectly. This fixes that.
Apologies!

Fixes incorrect Logfolder

---

assets/.gitignore
instapy/instapy.py
instapy/settings.py
tests/test_instapy.py

Fixes #1687 (and many others). Hopefully the error message will provide the user the information to update the chromedriver instead of raising issues.

Chromedriver validations

---

docker-swarm.yml

And this PR just includes a sample docker-swarm config, plus a link to a [tutorial](https://geek-cookbook.funkypenguin.co.nz/recipies/instapy/) in the "recipe" format I like :)

Add docker swarm config

---

instapy/like_util.py

_Found_ in #1365 thread;
_Mentioned_ in #1844 pull;
This is the _latest_ revision of the `get_links_for_tag` function (_last **revised** 25 days ago_) solving all of the possible conditions that could happen to `like_by_tags` by great feedbacks from 30 great ppl (_including me xD_) in #1365.

Enhanced version of `get_links_for_tag` function

---

instapy/instapy.py
instapy/settings.py

Create a pointer to this handler in settings
the use should be as follow:
```
from .settings import Settings
logger = Settings.logger
logger.info('sleep for long nap')
```

Add option to use logger outside instapy moudle

---

instapy/like_util.py
instapy/print_log_writer.py
instapy/settings.py
instapy/unfollow_util.py

Solves the error: `"Cannot read property 'graphql' of undefined"`
#1936
Tested features: Likes Follows and Unfollows using
* like_by_tags
* set_do_follow
* set_do_like
* interact_user_followers
* set_user_interact

⚠️ Quick fix for the new Instagram update

---

instapy/like_util.py
instapy/print_log_writer.py
instapy/unfollow_util.py

This reverts commit d82f70692efde57f551c088cdeb1a030cbcda528.
- Changes can be recovered from the branch "[array_removed_feature](https://github.com/joanroig/InstaPy/tree/array_removed_feature)"
- All code up-to-date with lastest changes
Tested features: Likes Follows and Unfollows using
- like_by_tags
- set_do_follow
- set_do_like
- interact_user_followers
- set_user_interact

⚠️Revert "Quick fix for the new Instagram update"

---

instapy/instapy.py

Returns back the changes done in #1782.
> Those lines mistakenly (_possibly_) were removed from main repository with the merge of #1682.

#1782 again

---

instapy/like_util.py

This fix the issue where interger are not generating a float on python 2.7 and earlier.

#1975 float 

---

instapy/like_util.py
instapy/util.py

Fix issue that can't get the possible_posts amount due to the css class changed to `g47SY`

Fix issue that can't get the possible_posts amount

---

instapy/util.py

Thanks everybody for the solutions as i ended up not having time to put it all together.  
Here is the aggregated fixes from #2131

Incorporate fixes for/from Issue #2131

---

instapy/login_util.py

Solves username in wrong field during login and handles update of instagram.

Instagram update fix

---

instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py
instapy/util.py

There is a situation when a user presses `CTRL+C` (or `CTRL+Break`) in order to terminate the program.
**Well** it is what most of us do. But there is a problem.
**followRestriction.json** is being dumped to the local file at `end` method which happens right after termination (**procedural** or **forcibly** (_e.g. by a user_)). Well, the problem raises here:
**At any** case, if that _JSON_ is not properly written (e.g. missing some double-quote or a comma and a closing curly brase) it will not be able to load in the next run cos it is corrupt.
**This problem has been** around so long and I had suggested a solution to fix it in many posts, (e.g., here https://github.com/timgrossmann/InstaPy/issues/1732#issuecomment-383390727)
But that solution **is to handle** that error, but not solve. …

Take cautions to provide healthy followRestriction.json usage. [PROPOSED to use DB]

---

proxy_extension.py

fixes bug when using proxy_extension
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

---

instapy/like_util.py
instapy/unfollow_util.py

Pr/2180 -> adjustments based on comments

---

instapy/instapy.py

Changes the logging to make the "too few images" problem more clear proposed by @uluQulu

change logging to proposal of @uluQulu

---

instapy/instapy.py

@uluQulu Here is the PR for the adding back the summary logging info to the CLI for interact_user_followers & interact_user_following that I suggested. #2206

Update instapy.py for CLI logging

---

README.md
instapy/instapy.py
instapy/relationship_tools.py
instapy/unfollow_util.py
instapy/util.py

+ And while writing it, I felt the need to modify Unfollow feature.
+ Out of the plan, with the request of a user I prepared a new feature: `interact_by_URL` and included it in this commit series
+ Wrote a `progress_tracker` from scratch to improve user awareness (_it's even better than `tqdm` module :P_).  
_For now, `progress_tracker` is integrated only to a pair of relationship tools._
+ Yes, it did not end up, I also added a new `highlight_print` definition to have a tasteful console output.
_Those are the notable changes that have happened so far._
Now I will tell briefly about the changes.
(_to save some lines and for much better view I've attached their links from README to see and read the details in full_)
+ [Grab `Followers` of a …

Relationship tools & stronger Unfollow feature & new `interact_by_URL` feature & lots of good revisions

---

instapy/instapy.py

more clear logs; add aborting;

---

instapy/commenters_util.py
instapy/instapy.py
instapy/util.py

Updated follow commenters procedure following recent Instagram updates.
Minor update in number of posts to scroll through.

Update of xpath + num_od_posts

---

instapy/instapy.py

I find particularly interesting the summary at the end of an action, but I miss the specification of that tipe of action was, so I added it.

Specify type of action in summary

---

instapy/unfollow_util.py

since splitting is part of eligible only
also optional pool added to function

follow pool "all" got the same user all the time

---

instapy/instapy.py
instapy/unfollow_util.py

1. Fix set set as dict
2. Separate dont_include users set at init(white list) from set during run time (like in set_dont_unfollow_active_users). this will remove the white list person from followers csv.

Fix set set as dict; introduce white_list; fix like amount wrong logic

---

instapy/instapy.py

i modify the while loop to check the numbers of the obtained links.
if the function return consecutively 0 for almost 10 times the loop will terminate.
in my case i stuck on the loop for hours before i realize that ...

avoid infinite loop when "get_links_from_feed" return 0

---

instapy/like_util.py

bugfix for issue https://github.com/timgrossmann/InstaPy/issues/2344

like image changed xpath

---

instapy/instapy.py

See [https://github.com/timgrossmann/InstaPy/issues/2322](https://github.com/timgrossmann/InstaPy/issues/2322)

Solve issue 2322

---

instapy/unfollow_util.py

sometimes when unfollow massively, a popup show up and ask for confirmation. 
with this little change we can press unfollow button again and go on with others unfollows correctly .

click on the unfollow button in the popup

---

instapy/like_util.py

better code for identify like button

better code for identify like button

---

instapy/unfollow_util.py

i modify a sleep time before and after click on unfollow for slower connections to show up and close the popup for unfollow confirmtion

update sleep time for slower connection

---

api.json

This an how api.json could be constructed, now generated from README.md.
As the described in: #2295.
Only the "Instapy features section".

WIP: Documented api in machine readable JSON

---

README.md
instapy/clarifai_util.py
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py
instapy/util.py

Hey guys,
Tonight could find some time and decided to share some useful bits with the community.
* Sorry for being late, @timgrossmann, but finally could prepare the promised change regarding _simulation_ and also improved it a little bit.
> As it's a quick preparation, will be great to have a look and ask questions on any unclear line.
Cheers 😁

Set of efficient revisions and fixes

---

instapy/unfollow_util.py

IG changed location of follow buttons
Issue: Following problem ? #2461

FIX: updated xpath in unfollow util

---

instapy/comment_util.py
instapy/commenters_util.py
instapy/like_util.py
instapy/util.py

while trying to remove duplicated previous method (list(set(...
Reordered the user links.
Fixed.

fix get_links_for_username always shuffling the order

---

instapy/like_util.py

Issue: #2484
Fixed by @uluQulu

FIX: variable reference issue in get_links_for_username

---

instapy/commenters_util.py
instapy/instapy.py

Update xpath in likers_from_photo method

---

instapy/instapy.py

align logs to correct place

---

instapy/database_engine.py

Fix for 'NoneType' object is not iterable

added Sleep

---

instapy/database_engine.py
instapy/instapy.py
instapy/settings.py
instapy/unfollow_util.py
instapy/util.py

Small refactor on Create Database and Get Database Logic on instapy/database_engine.py
Separated logic into small functions for better redability and removed comments (functions names have full name now)
Separated SQL into constants
Fixes #2588

Fix Problem on Create Database

---

README.md
instapy/instapy.py
instapy/like_util.py
tests/test_like_util.py

Hello,
I added the possibility to add a mandatory word list.
Example : 
```
session.set_mandatory_like(['#food', '#instafood'])
session.like_by_locations(['213099780'], amount=100)
```
Like photo's in location "213099780" only if contains the hashtags "#food" and "#instafood".

Feature - mandatory like

---

instapy/database_engine.py
instapy/instapy.py
instapy/settings.py

Popped up from #2611 I saw a bug and started to write a fix for it then saw a big gap in the logic from I designed to end result which missed lots of considerations regarding the code strength.  
Fine, I HAVE solved it once more but now I'm afraid that I wrote this dedicated DB engine (_maybe it was so dedicated_) 😝
#2611:
+ In case of there is already an **instapy.db** file in the old structure (_just `statistics` table_) it will neither make a new database or make required new tables.
>It was just making the given tables only once there existed no any database file in the given location.
This is what I talked about smooth design, @timgrossmann 🙂
_If you have any questions about other changes (_non-visual_), please let me know!_
-----------
Cheers 😁

Solve misbehaviours of #2605 🐝

---

instapy/settings.py

if you need more then one chromedriver (for development purpose) you can rename it as :
chromedriver_linux
chromedriver_osx
chromedriver_windows
and you can put all in assets directory

use different chromedriver for os environment

---

instapy/commenters_util.py
instapy/login_util.py
instapy/relationship_tools.py
instapy/unfollow_util.py

A trivial mistake of mine (_mostly_) 🤤
Thanks to @Edhim to raise it at #2663 in a great feedback.
--------
Cheers 😁
----------

Fix: convert exception messages into a string before encoding AND some other small fixes

---

docs/How_to_Raspberry.md

added instructions for how to install with raspbian stretch lite 4

update "how to raspberry" docs

---

instapy/unfollow_util.py

Fix a bug that reported by @bianpratama from #2727 .

fix a minor bug could cause cant get the userid from post page

---

instapy/unfollow_util.py

Fix error //div[text()='Followers' or text()='Following']/following-sibling::div")

fix error #2757

---

instapy/util.py

fixes for #2740

---

instapy/unfollow_util.py

Fix the StaleElementReferenceException error mentioned in #2768 #2780 #2772 (maybe others as well). Created based on comment by @uluQulu in #2745. Worked for me as of August 27.

Fix StaleElementReferenceException

---

instapy/util.py

The issue reported by @sionking from #2817

Fix a potential bug that remove more than one line from the followedpool csv

---

instapy/comment_util.py

replace: //a[@role='button']/span[text()='Comment']/..
to: //button/span[@aria-label='Comment']

Xpath to focus in the comment field

---

README.md
instapy/instapy.py

update instapy to disable image load in chrome webdriver from #1364

---

README.md

typo fix #2966

---

README.md

Replacing content of #2248

---

README.md

Also changing some points in the quickstart.py
Any ideas on how we could remove the exception part out of the quickstart file?
@uluQulu @sionking @CharlesCCC

Docu update with chromedriver/db relocation

---

README.md
instapy/comment_util.py
instapy/instapy.py

Validate post have at least one valid word from comments_mandatory_words list.
Do comment on it if does.

comments mandatory words

---

instapy/util.py

and also if not at the beginging of line we shall check whitespace before username:
YusernameX
Y = whitespace if not at start of line
X =  whitespace/dot/newline

REMOVE USER FROM POOL FIX: Now we check that there is a whitespace/dot/newline at the end of username

---

instapy/instapy.py
instapy/util.py
quickstart.py

Here is a new version of quickstart script usage:
https://github.com/uluQulu/InstaPy/blob/master/quickstart.py
+ It will **auto**-login; You don't need to write down `session.login()` line
+ It will **always** end the session [using `session.end()`] at the end of the script or after some interrupt.
+ User will **only** provide _login credentials_, _instantiate InstaPy class_ and then _write down the activity flow_ [actions and settings]
Shortly,
```python
#imports
from instapy import InstaPy
from instapy.util import smart_run
insta_username = ''
insta_password = ''
session = InstaPy()
with smart_run(session):
session.set_relationship_bounds(enabled=True, potency_ratio=1.07)
session.like_by_tags(["natgeo"], amount=10)
```
That's it!
**While inside** `smart_run()`, now after a keyboard …

Ease the quickstart script by moving login() & end() methods alongside advanced exception handling into a separate function- smart_run()

---

instapy/database_engine.py
instapy/instapy.py
instapy/relationship_tools.py
instapy/unfollow_util.py
instapy/util.py

Just replacing `occured` to `occurred` on texts, fixing typo
Issue #2572

Spelling mistake "occured"

---

assets/business_categories.md

Updated business_categories.md

---

instapy/instapy.py

only cosmetics work.
But more important this will modulate the comments Technic so each user can create his uniqe coding without modifying the all code.
Enjoy.

restyling comments

---

instapy/util.py

Thanks @anna-osipova for pointing this out
@sionking For the more generally applicable fix

applying @sionkings proposal about getting post count

---

README.md
instapy/clarifai_util.py
instapy/instapy.py

Added support for the majority of Clarifai’s public models. Given that the API response for `Focus`, `Face Detection`, `Face Embedding`, and `General Embedding` is different from other models, I did not include them at this time. 
I have also added support for using Clarifai **workflows** (a single API call for checking an image against up to 5 models). With the changes, a user can choose which specific model (or models) they wish to check an image against. If a model isn’t chosen, the general model is used. It’s worth noting that you can either chose to check an image with a workflow or with one or more models.  
In the interest of simplicity,  I made the decision that `full_match=False` will always be used when checking tags against `img_tags_skip_if_contain`. That is, if any tag in …

Clarifai Models and Workflows

---

instapy/util.py

Referring to issue #2824, this fix works on my system (a mac).
I suppose is ok also for everyone else.
If not, try to find the best fix as, as is, will not write the file.

Blacklist is still not fixed

---

instapy/login_util.py

After login user see popup Turn On.
If InstaPy can find it, it dismiss it.

Dismiss Turn-On popup

---

instapy/clarifai_util.py
instapy/database_engine.py
instapy/feed_util.py

Fixed a couple of Line length, Empty lines, Trailing commas, Line breaks, and 
parentheses formatting issues.

Reformat a couple pieces of code with Black

---

instapy/unfollow_util.py

Change every place we have following/ followers count to one function

---

README.md
instapy/clarifai_util.py
instapy/instapy.py
instapy/unfollow_util.py

read the title.
@timgrossmann Documented for first time hope it is fine :)

Use proxy to access clarifai; return clarifai tags to caller

---

instapy/clarifai_util.py
instapy/instapy.py

Fixed the `get_clarifai_tags` function to properly extract all tags from the celebrity and demographic models response.

Clarifai Util: Fix for Tag Extraction for Celebrity and Demographics Models

---

instapy/clarifai_util.py
instapy/instapy.py

Fixed indentation in `clarifai_util` and added definition for `clarifai_proxy` inside `__init__`

Fixed indentation in clarifai_util 

---

instapy/login_util.py

#3229  Unable to login - issue

Updated xpath for "log in" link

---

CHANGELOG.md
README.md
instapy/instapy.py
instapy/like_util.py

Interact with tagged images of users, and validation of a user to be optional

Feature: interact with tagged images of users

---

CHANGELOG.md
instapy/util.py

This PR add support for the blacklist check.
The actual code does not work for me on python 2.7, my modification works perfectly.
Take care

Update to let Blacklist Actually be referred

---

instapy/util.py

Based on commit of #3318 fix by @uluQulu

Quick fix for a bug off cc3b4f0

---

instapy/commenters_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/quota_supervisor.py
instapy/util.py

collaborative PR with @Malusovium to fix E722 (PEP8) code style and improve code quality. Going to update Travis next.

Pep8 E722 fix with @Malusovium contribution

---

CHANGELOG.md
instapy/login_util.py

the PR will fix this bug: 
https://github.com/timgrossmann/InstaPy/issues?utf8=%E2%9C%93&q=is%3Aissue+cookie+file+not+found+

cookie file not found bugfix

---

instapy/login_util.py

Hi, I was had the error. Then i did set Headless to false and debug myself. So i realized after cookie inserted the browser was staying on the login page. So everything goes wrong.

Issue with cookie for user Creating new cookie fix

---

CHANGELOG.md

update for mandatory_words

---

instapy/login_util.py

I was having this issue:
```bash
➜  InstaPy git:(language_switch_fix1) ✗ python quickstart.py
Traceback (most recent call last):
File "/Users/converge/Documents/workspace/InstaPy/instapy/util.py", line 667, in click_element
element.click()
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
self._execute(Command.CLICK_ELEMENT)
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
return self._parent.execute(command, params)
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in …
```

language switch fix

---

CHANGELOG.md
instapy/instapy.py

As requested by @timgrossmann fix for aborting on follow users following/follower.

Aborting Fix

---

CHANGELOG.md
instapy/commenters_util.py

should hopefully not modify existing functionality
mentioned in issue https://github.com/timgrossmann/InstaPy/issues/3415
Also, rephrases a misleading log line.

Fixes likers_from_photo when liked counter is "liked by X and N others"

---

CHANGELOG.md
instapy/instapy.py
instapy/print_log_writer.py
instapy/unfollow_util.py
instapy/util.py

-- remove https://i.instagram.com/api/v1/users/{}/info/ as it not working and killing the unfollow with error
-- fix logging uncertain
-- fix get active users  when Video have no likes button / no posts in page

remove  api call; fix logging uncertain; some more error catching

---

docs/How_to_Raspberry.md

How to Raspberry with Python 2.7 & Python 3

How to Raspberry with Python 2.7 & Python 3

---

quickstart_templates/README.md

Simple readme update for the quickstart templates as some of the limits in some of the templates are quite dangerous to have depending on various factors.

Update Quickstart Readme

---

CHANGELOG.md
instapy/unfollow_util.py

in case:
time_stamp, user
user
the user without timestamp will use the timestamp of privious user.

fix time_stamp will be last follow profile

---

CHANGELOG.md

Following up on #3637 this adds the changelog entry for the layout adjustments

PEP8 Update CHANGELOG.md

---

README.md

- Smaller Paypal.me link
- Add open collective link

Update readme support part, add open collective

---

CHANGELOG.md
README.md

Updating the proxy documentation.

Proxy Readme update

---

CHANGELOG.md

Sorry guys, forgot the changelog update again...

changelog update for new pyyaml version

---

instapy/instapy.py
instapy/unfollow_util.py

3707 PEP8 Changes

---

instapy/instapy.py
instapy/unfollow_util.py

Do not merge this till you have merged #3709.
This is just some minor fixes and security stuff I noticed when doing the PEP8 changes, if InstaPy is closing for example or to make sure it feedsback correctly to things like QS

3707 small bug fixes

---

CHANGELOG.md
docker-prod.yml
docker_conf/python/Dockerfile

Docker now mount correctly the volume, and works properly with chromedriver installed under the assets folder

Fix on docker prod

---

CHANGELOG.md
docker-compose.yml

This is a fix to docker-compose.yml to comply with the changes in the Dockerfile applied by #3711 
It addresses and fixes issue #3718

Fix docker-compose.yml according to new Dockerfile from #3711

---

README.md

Update preferred installation to use builtin venv and not virtualenv

---

CHANGELOG.md
instapy/unfollow_util.py

Dialog box has changed, XPath was affected by that.

Fix 'Failed to load desired amount of users!' issue

---

CHANGELOG.md
instapy/commenters_util.py
instapy/relationship_tools.py
instapy/util.py

I have been reported it occurred with `follow_likers()` feature.
Fixes are applied to the `likers_from_photo()` function and each change is explained in the commit description.
---
Cheers 😁
---

Fix "_Unable to locate element: ...xpath","selector":"//div[text()=\'Likes\'..._" error

---

CHANGELOG.md

It's a little bit changed form of the #3722 PR name.

Update Changelog for/off #3722

---

CHANGELOG.md
README.md
instapy/file_manager.py
instapy/util.py
requirements.txt

In requirements.txt I used the specific chromedriver version 2.44 since 2.45 gets me an chromedriver error:  
Chromedriver version needs to be between 70-73.
I don't know if this error is only present for me.
Otherwise we need to change `instapy-chromedriver==2.44` to `instapy-chromedriver>=2.44` in file requirements.txt.
I also converted a random method description string into a pydoc string. Just noticed this while scrolling a file :)

added instapy-chromedriver package if no chromedriver is in path

---

README.md

restructuring parts of the README

first changes in readme

---

docs/How_to_Raspberry.md

Some fixes.

---

README.md

- Fix Contribution link broken 🛠

Fix Contribution link broken

---

docs/How_to_Raspberry.md

Support only for Pi3b. No support for older models.
Support for Raspbian Stretch with desktop, no support for Noobs.

Updated Tutorial

---

CHANGELOG.md
instapy/__init__.py
instapy/unfollow_util.py

New xPath for Follower Dialog Box
File changed:  instapy/unfollow_util.py

Fix for scrollIntoView error

---

instapy/unfollow_util.py

Tested on chrome on mac OS high Sierra

fixing bug introduced by 8e4fb14

---

CHANGELOG.md
README.md
instapy/browser.py
instapy/instapy.py
instapy/login_util.py

Enable Proxy Authentication for Firefox.
I'm proposing this PR to test it a little more. I still need to write documentation for the feature.

Proxy auth (Firefox)

---

CHANGELOG.md
instapy/instapy.py
instapy/like_util.py
instapy/unfollow_util.py
instapy/util.py

Thanks to @TarekJ03 for highlighting this expected behaviour 🐬

Enable users interact by the comments of their own profiles.

---

CHANGELOG.md
instapy/login_util.py

there is a new Log In button location. Should we add it on Changelog?

xpath update for Log In button

---

CHANGELOG.md
instapy/commenters_util.py

fixes https://github.com/timgrossmann/InstaPy/issues/4032
fixes #2646
fixes #3976

For likers/commenter less than 10 it was not fetching any users as it was breaking out before that.

---

CHANGELOG.md
instapy/__init__.py
requirements.txt

Allow InstaPy to update chromedriver to newer version than 2.44
fixes #4043

update requirement for instapy-chromedriver

---

instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/settings.py
instapy/unfollow_util.py
requirements.txt

We all have been seeking  better analytics for Instapy.
I decided to Integrate InfluxDB which is a No-SQL time series database.
Inputs are based on the time.
I created a Singleton Class in settings which creates a connection to the db.
It is initialised in instapy.py
I also created functions that you can use to add values in the db or change db.
Functions can be added very easily
To use the SingletonClass just import `from .settings import InfluxDBLog`
Then in your file just call ÌnfluxDBLog().addEntry(args)` to add a new entry in the DB.
in order to have this working please install InfluxDB on your computer and create a user.
For it to be activated you must in the instapy constructor input your InfluxDB username, password, host, port and database name.
In order to visualise the data just …

InfluxDB Integration

---

CHANGELOG.md
README.md
instapy/database_engine.py
instapy/instapy.py
instapy/pods_util.py
instapy/settings.py

Implemented https://github.com/timgrossmann/InstaPy/issues/3868
Currently time window is set to 12.5 hours, will reduce it going forward based on adoptation.

Feature pods

---

README.md

In eg Function set_reply_comments replaced in line 787 with the correct fuction name set_comment_replies.

Corrected a function name in the examples

---

CHANGELOG.md
instapy/unfollow_util.py

please refer to me talking we my self:
https://github.com/timgrossmann/InstaPy/issues/4103
This is a major bug in core functional.
** this has not been tested for **follow** please assist in testing.
**ANY CODE THAT LOOK FOR GENERAL TEXT IS UNSAFE AND NEED TO BE AVOIDED**

fixing verify action for unfollow and follow actions.

---

CHANGELOG.md
instapy/__init__.py

Prepare `dev` branch for merge into master

update instapy version

---

CHANGELOG.md
README.md
instapy/__init__.py
instapy/browser.py
instapy/commenters_util.py
instapy/database_engine.py
instapy/instapy.py
instapy/like_util.py
instapy/pods_util.py
instapy/settings.py
instapy/unfollow_util.py
instapy/util.py
requirements.txt

- Allowing `follow_by_tags` to interact with the user
- Context manager to interaction calls in `like_by_tags` and `follow_likers`
- Engagement pods feature 🙌 
- Smart Hashtags based on locations `set_smart_location_hashtags`
- Verify action for unfollow and follow actions
- Browser abstraction and Decorator that handles Selenium Browser exceptions by reloading
- Add delay unfollow of follow backers
- Expose `threaded_session` of Instapy.end()
- `follow_likers` always fetches zero likers
- Prevent division by zero in `validate_username`

InstaPy 0.3.0

---

instapy/__init__.py
instapy/like_util.py

Will be re-added once scope is fixed

removed retry decorator

---

instapy/__init__.py
instapy/browser.py
instapy/like_util.py

- Comment conversion in browser file
- Comment usage of wait_for_... in like_util

Hot fix problems with browser abstraction class

---

instapy/util.py

This hot fix improves multiple things:
- Proper usage of xpath tree architecture to find both the likers count and the likers button. This also increases speed because there are not as many checks, process of getting active users will be much faster now. 
- Process of finding and skipping videos much faster and reliable as well.

get_active_users hotfix

---

instapy/browser.py
instapy/instapy.py
instapy/login_util.py

sets language on the browser (Firefox and Chrome (already implemented) preferences

sets language on the browser (no clicks required)

---

CHANGELOG.md
instapy/login_util.py

One of the last releases added a change to Language change on login page. Did also remove a reload_webpage() call in login_user() function, that is/was needed to correctly load the IG page after cookie had being added to the browser session.
This adds the import and reload again.

Fix: (re) adding page_reload, after cookie load, on login_user()

---

README.md

Minor changes in the README to improve readability.

Improve the README readability

---

CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py
requirements.txt

Tidied up the documentation white space
Added information regarding the `nogui` parameter.
Also, since the `pyvirtualdesktop` lib used only supports Linux based systems, I've removed requirement for windows as well as outputting a relevant error message if the parameter is used on Windows.

Shed some light on the nogui parameter

---

CHANGELOG.md
instapy/database_engine.py

Assignment to a variable occurs multiple times without any intermediate use of that variable
Multiple assignments to a single variable without an intervening usage makes the first assignment redundant. Its value is lost.

Variable defined multiple times

---

CHANGELOG.md
instapy/instapy.py

Now when user entered wrong login data and he uses script, which will interact by comments, instapy will end session instead of starting interaction.

Fix interact_by_comments

---

CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py
instapy/util.py

Threaded session ending without exception `ValueError: signal only works in main thread`

End threaded session

---

CHANGELOG.md
DOCUMENTATION.md
instapy/database_engine.py
instapy/instapy.py
instapy/pods_util.py

Here I have added two features:
1. added different levels for amount of comments desired to receive. (10%,30%,90%)
2. addressed the issue to prevent multiple times commenting on same post.
The featues discussed [here](https://github.com/timgrossmann/InstaPy/pull/4308#issuecomment-483522098) will be done after merging these.
There has been serverside changes made including db fields. But it is expected to be fully backward compatible.
@timgrossmann [Here](https://github.com/InstaPy/instapy-pods-server/pull/2) are the corresponding server side changes.

Feature finetuning comments for pods

---

CHANGELOG.md
instapy/__init__.py
instapy/comment_util.py

Bug: https://github.com/timgrossmann/InstaPy/issues/4409
Reused similar logic already written in `like_util`

Bug: fixing commenting issue #4409

---

CHANGELOG.md
instapy/instapy.py

Found this issue. Not sure, if we are misssing more like these.
Please test the dev with all the merged changes together.

like_image in dev has this arg

---

DOCUMENTATION.md
README.md

This PR is about reorganizing documentation:
- Adding TOC (Table of Contents) to README.md to be easiest to navigate between sections
- Adding GUI section to README.md (@breuerfelix I think `GUI` should be rename to `WebUI` or to `Web Interface` to be clearer for end users because I'm not sure everyone out there know what a GUI means 😄 ) to let people know about the project
- Moving Docker section from DOCUMENTATION.md to README.md because it was not easy to find for new users

Reorganizing documentation

---

instapy/unfollow_util.py

Fix for session.follow_user_following() broken behavior #4517

---

CHANGELOG.md
DOCUMENTATION.md
instapy/__init__.py

Documentation now includes how to deal with Selenium common exceptions and what to look for, and how to fix when the errors are thrown.

Dealing with Selenium Errors

---

CHANGELOG.md
instapy/__init__.py
instapy/login_util.py

The code causes invalid argument exception.

Fix Argument Being Interpreted as Sequence

---

CHANGELOG.md
instapy/browser.py

Addresses and Fixes issue https://github.com/timgrossmann/InstaPy/issues/4607

Always start chromedriver with --no-sandbox

---

instapy/util.py
instapy/xpath_compile.py

- xpath update
- graphql information collect update

dont_unfollow_active_users feature fix

---

DOCUMENTATION.md
instapy/browser.py
instapy/instapy.py
requirements.txt

This is a really basic implementation but it is better than nothing.
We still have to discuss wether it is okay to always have a random user agent enabled or per default just use the latest chrome agent.
Let the discussion start!

ability to choose a random user agent, latest chrome per default

---

.flake8
instapy/browser.py
instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/pods_util.py
instapy/story_util.py
instapy/util.py
tox.ini

changes:
- extract flake8 config
- only run one flake command in tests
- fixed some lines too long errors
- fixed a forgotten import
- fixed a logger error
- fixed deprecated regex

flake8 enhancement + linter fix

---

DOCUMENTATION.md
instapy/browser.py
instapy/instapy.py
instapy/story_util.py
instapy/util.py

small fixes on stories:
- ensure that we work with tags where input was lower/upper case (for example #InstaGood), reported by JayPixx
- added action_delays for story (suggested by JayPixx)
- updated the TOC of the documentation (reported by Leak)

Stories: various small fixes

---

instapy/instapy.py
instapy/login_util.py
instapy/xpath_compile.py

- speed up the login process by decreasing the implicit wait to 5 seconds
- new approach for connection verification, it will check if we can navigate, and then check Instagram.com website status

Speed up login process and Connection check feature

---

DOCUMENTATION.md
instapy/instapy.py
instapy/login_util.py
instapy/xpath_compile.py

- adds more information about the login process
- adds challenge login auto-detection by url (deletes the bypass_suspicious_attempt parameter)'

Credentials check enhancement

---

instapy/instapy.py

Log of the problem:
INFO [2019-07-24 10:38:41] [xxx]  Username [1/1]
INFO [2019-07-24 10:38:41] [xxx]  --> b'yyy'
INFO [2019-07-24 10:38:41] [xxx]  ---> yyy has already been followed 1 times
INFO [2019-07-24 10:38:41] [xxx]  username actions: following=False commenting=False liking=False story=True
INFO [2019-07-24 10:38:41] [xxx]  Getting yyy image list...
INFO [2019-07-24 10:39:09] [xxx]  Cannot detect post media type. Skip https://www.instagram.com/p/zzz/
INFO [2019-07-24 10:39:09] [xxx]  **Post [1/2]**
INFO [2019-07-24 10:39:09] [xxx]  https://www.instagram.com/p/zzz1/
INFO [2019-07-24 10:39:13] [xxx]  Image from: b'yyy'
INFO [2019-07-24 10:39:13] [xxx]  Link: b'https://www.instagram.com/p/zzz1/'
INFO [2019-07-24 10:39:13] [xxx]  Description: …

interact bug fix

---

DOCUMENTATION.md
instapy/browser.py
instapy/settings.py
instapy/story_util.py
instapy/xpath_compile.py

This is a better version of stories:
- works in simulate = True or simulate = False, even if no video playback is available
- fixed the user agent that was missing in the graphql queries

Rewrite of stories

---

instapy/commenters_util.py
instapy/xpath_compile.py

fix xpath when there is now 2 links on a post: Liked by xxx and 17,234 others
we check first if the 2nd link is present (others) if not we fallback to the old way

fix_xpath_likers_from_photo

---

instapy/browser.py
instapy/instapy.py
requirements.txt

- adds mobile mode
This is required for the create_post feature (it's a Pull Request at the moment). Next feature to be developed using the mobile mode is Direct Messaging.

Mobile mode

---

instapy/comment_util.py
instapy/commenters_util.py
instapy/feed_util.py
instapy/like_util.py
instapy/login_util.py
instapy/print_log_writer.py
instapy/story_util.py
instapy/unfollow_util.py
instapy/util.py

- Create a connection state every new information about connection is updated to a JSON file.
- Screenshots is implemented, every time we do a server call or state update, a new screenshot is taken. Screenshots are rotative and are saving the last 3 screenshots, it means, the older screenshot is replaced with the newest one.
- Challenge Security Code can now also be requested from the `username.json` file as 
```json
{
"challenge": {
"security_code": 123456
}
}
```
These enhancements open place for Dashboard and GUI further improvements.

Connection state

---

DOCUMENTATION.md

fixed the TOC that was not anchoring correctly (requested by @converge)

doc fix on instapy-stories

---

DOCUMENTATION.md
instapy/instapy.py
instapy/pods_util.py
instapy/settings.py

The pods server is down for many months due to heavy traffic. This may finally get it up and running again.
@timgrossmann : I have added 
contact.timgrossmann@gmail.com and help.instapy@gmail.com as owners for each of the servers.
This change also has a minor renaming of topic `beauty` to `fashion `

pods - topic specific dedicated servers

---

instapy/unfollow_util.py
instapy/xpath_compile.py

Fix the verify action that was not working anymore on mobile due to being an icon and not a button with text

Fix verify action

---

CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py
instapy/login_util.py
instapy/xpath_compile.py

hey @alxhoff, thanks for your PR, I made some changes and would like to ask you to try this approach, what do you think?

@Alxhoff: bypass suspicious attempt (by phone or by email)

---

instapy/instapy.py
instapy/login_util.py
instapy/xpath_compile.py

Allows SMS to be set as the default security code authentication method

---

instapy/commenters_util.py
instapy/instapy.py
instapy/print_log_writer.py
instapy/relationship_tools.py
instapy/story_util.py
instapy/unfollow_util.py
instapy/util.py
instapy/xpath_compile.py

After changing of user agent(iphone x), instagram web page was changed. 
Fixed xpaths and logics that make follow_commenters function worked. 
Updated the checking of private user logic.
Fixed followers count xpath bug.
Updated the graphql script to get the ProfilePage information.
About the new commit:
I realised that, on some Instagram account, the old "window._sharedData.entry_data.ProfilePage[0]" variable is still working and the new one is not working. That's why I added a backup plan. It checks if "window.__additionalData" is defined, if not it tries to get info with "window._sharedData.entry_data.ProfilePage[0]".

Xpath, script and logical fixes of the new update

---

instapy/like_util.py

This PR is similar to https://github.com/timgrossmann/InstaPy/pull/4892 to fix some of the UA updates.
close #4882

Use _additionalData to pull graphql info

---

instapy/commenters_util.py
instapy/like_util.py
instapy/util.py

Fixes: #5018 #5017 #5013 #5006

Bug fixes about StaleElementReferenceException and graphql scripts

---

instapy/login_util.py

in https://github.com/timgrossmann/InstaPy/issues/5035#issuecomment-529238015

fix #5035 according to comment from @fazilakbulut

---

instapy/instapy.py

Add docstring and small refactor for interact_user_followers()

---

instapy/exceptions.py

Remove unnecessary `pass` statement.

Refactor exceptions.py

---

README.md

Have improved the major INSTAGRAM image size with some alignments at the end and have also improved UserId and Password for better understanding of the user.

IMAGE SIZE IMPROVEMENTS AND ALIGNMENT

---

instapy/instapy.py
instapy/unfollow_util.py

unfollow() - Manage **InstapyFollowers** and **nonFollowers** parameters when both are True
validate_user_call() - swap order of **self.skip_bio_keyword**  with   **self.dont_skip_business_categories**

Update unfollow()  and  validate_user_call()

---

DOCUMENTATION.md

Make it more specific about how to use proxy.
Issue:https://github.com/timgrossmann/InstaPy/issues/5106

Update telegram integration examples.

---

README.md

fix to typo - offical -> official

---

instapy/unfollow_util.py

The "allFollowing" filter on unfollowing method now works. It works like nonFollowers filter: it grabs following by method on relationship file

Fixed allFollowing

---

instapy/util.py

Fix for error at startup when `want_check_browser` was introduced

Update for util.py

---

CHANGELOG.md
DOCUMENTATION.md
instapy/__init__.py
instapy/instapy.py
instapy/login_util.py

* https://isitdownorjust.me website seems to be down
* InstaPy fails the instagram server check and then aborts
* Commented out check in login_util.py until a better website checker is found

Disabled instagram server checking #5207

---

README.md

Deprecated text in link to InstaPy Dashboard

External Tools: InstaPy Dashboard Deprecated

---

CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py
instapy/util.py
tests/resources/invalid_target_list.txt
tests/resources/valid_target_list.txt
tests/test_file_handling.py

Hello, I was assigned to implement the ability to parse text files containing target users, hashtags, comments etc in order to use it with functions which accept lists as given parameters. This will be a part of a university assignment of mine as I also mentioned on issue #5396.
**Functions added:**
file_handling in util.py
target_list in instapy.py
_PS: At first, I implemented file_handling function inside instapy.py (with only a few changes) & that also worked, but I had to change that implementation because I wasn't able to do some unit testing._
**Unit testing:**
test_file_handling.py in tests folder
invalid_target_list.txt in tests/resources folder
valid_target_list.txt in tests/resources folder
**Example of using new feature in quickstart.py**
```
""" Quickstart script for InstaPy …
```

Insert target users, hashtags etc from text file - Issue #5396

---

DOCUMENTATION.md

Smart-hashtags and smart-location-hashtags links in `Follow by Tags`  section were not working. Fixed it.

Fixed 2 broken links

---

instapy/instapy.py

cloudfront.net address was no longer reachable (404)

fixed problem with smart_hashstags

---

DOCUMENTATION.md
instapy/comment_util.py
instapy/instapy.py

This pull requests includes two main topics:
1. It resolves an issue with commenting which is not working because the data structure that InstaPy is using for reading the number of current comments and if comments are enabled/disabled for the post was changed.
2. It adds support and documentation for two features related to commenting:
* Add support for groups of words in comments_mandatory_words
* Add support for conditional comments so that different sets of comments can be associated with different mandatory words. This allows for much better contextual comments that are actually relevant for the content of the image and I believe will result in better interactions.
While implementing this I tried to clean up some of the commenting related code in all the activities but there is …

Fix commenting issues and add a new conditional comment feature

---

instapy/login_util.py
instapy/xpath_compile.py

After testing this tool locally, I found that the Log In button in my location (Bulgaria) was a <div> element. This patch adds handling for that case.

Add another xpath for retrying the initial log in

---

CHANGELOG.md
instapy/login_util.py

We can't launch the bot because https://isitdownorjust.me/instagram-com/ has a lot of issues.

Fix  "Check Instagram.com Status"

---

CHANGELOG.md
instapy/__init__.py
instapy/comment_util.py
instapy/instapy.py

Release of version`0.6.9` with community fixes

New release

---

CHANGELOG.md
instapy/quota_supervisor.py

Corrected typo updating configuration object. Changed nofity into notify

Corrected typo updating configuration object. Changed nofity into notify

---

CHANGELOG.md
instapy/xpath_compile.py

Solves: https://github.com/timgrossmann/InstaPy/issues/5287

Update xpath for like/unlike and comment

---

CHANGELOG.md
DOCUMENTATION.md
instapy/comment_util.py
instapy/instapy.py
instapy/like_util.py
instapy/util.py
tests/comment_util_tests.py
tests/util_tests.py

Generalize the complex mandatory keywords defintion to be used anywhere mandatory keywords are supported.
Add support for mandatory_bio_keywords in set_skip_users

Generallize mandatory words and add mandatory_bio_keywords 

---

DOCUMENTATION.md
instapy/comment_util.py
tests/comment_util_tests.py

Enhance the previously added compound comment structure and set_comments
Added tests to verify the above functionality

Further enhancement to set_comments

---

instapy/comment_util.py
instapy/util.py
tests/comment_util_tests.py
tests/util_tests.py

Signed-off-by: Tim Grossmann <contact.timgrossmann@gmail.com>

reformat with black

---

CHANGELOG.md
instapy/xpath_compile.py

The feed structure has changed and required a fix when getting the list of links of images to like

Fix like_by_feed() xpath

---

instapy/browser.py

Signed-off-by: Tim Grossmann <contact.timgrossmann@gmail.com>

blackify new version

---

CHANGELOG.md
instapy/feed_util.py

This function had a few redundant bits - this is a cleaner version.

Improved function readability

---

CHANGELOG.md
instapy/__init__.py

- Generallize mandatory words and add mandatory_bio_keywords
- Update xpath for like/unlike and comment
- Fix `like_by_feed()` xpath
- `get_like_on_feed()` improve function readability
- "UnboundLocalError: local variable 'commenting_approved' referenced before assignment" error when bot tries to comment
- Typo updating configuration object. Changed nofity into notify
- Add specific firefox preference agent data to prevent error
- Smart location url 
- Error "Hide Selenium Extension: Error" mentioned in #5304
- XPATH for like svg

Release 0.6.10

---

CHANGELOG.md
instapy/xpath_compile.py

Looks like IG changed the HTML structure again so adjusting the xpath to accomodate

Adjusting the get_links xpath for yet another change

---

CHANGELOG.md
instapy/util.py

This will also save on server calls as the last one would failed and reload the page everytime.

Fix for obtaining user id.

---

instapy/unfollow_util.py
instapy/util.py

Signed-off-by: Tim Grossmann <contact.timgrossmann@gmail.com>

blackify fixes

---

instapy/util.py

Python 3.5 problem with f strings

change f string to format

---

CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py

Hello 
I have noticed that whenever I start a session the tag list is used in the order the values were added, this is not a problem if the session is not terminated and restarted in a long period of time. However, if the InstaPy session is terminated for any reason the tag list will be called again but using the same order values.
With this change session.like_by_tags list is randomized when the session is created, adding extra entropy to the logic. If user doesn't use the new flag the logic remains the same as before, so the functionality is not affected.
DOCUMENTATION.md was changed to reflect the new flag for session.like_by_tags:
`use_random_tags`: The tags that will be searched for and posts will be randomized
Extra spaces were removed, doesn't affect readability.
`tag[1-16]` in the …

Use random tag list for session.like_by_tags

---

instapy/browser.py
instapy/comment_util.py
instapy/feed_util.py
instapy/instapy.py
instapy/like_util.py
instapy/quota_supervisor.py
instapy/relationship_tools.py
instapy/story_util.py
instapy/time_util.py
instapy/unfollow_util.py
instapy/util.py

Signed-off-by: Tim Grossmann <contact.timgrossmann@gmail.com>

blackify_new

---

CHANGELOG.md
instapy/like_util.py

before it was after every 10th like

check if liking activity was blocked after every like

---

.gitignore
CHANGELOG.md
DOCUMENTATION.md
instapy/instapy.py
instapy/like_util.py
instapy/util.py

Problem:
- `accept_follow_requests()` asserts if user requested to accept more than 10 followers. This is because an xpath cannot be reached, lets said they have 11 follower but only 10 are visible since User requested to accept 20  the 11 follower will be tried to be accepted but before that an assert will be thrown.
- Adde to `like_by_locations()` the `randomize` flag, #5803 
- There are some messages for referenced variables before assignment.
Solution: 
- Call `scroll_down()` after follower accepted, with this new def the window is scrolled down after accepting a follower.
- Added `like_by_locations()` with `randomize` flag
nit changes:
- Sorted imports, to make code readable
- Defined local variables ( ie: 'unfollow_state') to fix message for referenced before assignment
- Added …

Accept follow requests assert

---

DOCUMENTATION.md
README.md
instapy/browser.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/unfollow_util.py
instapy/xpath_compile.py

Hello all,
===============================================================================
broser.py:
Added `firefox_options.log.level` = `geckodriver_log_level` for debugging, normal user will use by default 
`info` level
nit: Imports were ordered
===============================================================================
instapy.py:
Modified `followed.txt` log to append information
Added `geckodriver_log_level` for debugging traces, normal user will use by default 
`info` level
nit: Imports were ordered
handled unbounded variables
fixed some comments were double quotes were not necessary
===============================================================================
like_util.py:
`like_image` now needs to handle images and videos, for now just informing to the user
that a video was …

Subject: instagram_title_fix and other fixes

---

.github/pull_request_template.md
CHANGELOG.md
docs/instance-settings.md
instapy/comment_util.py
instapy/instapy.py
instapy/login_util.py
instapy/xpath_compile.py

Hello all,
Hope you doing well,
Added Two Factor Authentication feature, intended for protected
accts. If the acct is not protected this feature will be ignored and will
be unnoticed. This feature basically should be used to bypass the 
extra security configuration used by the InstaPy user.
- comment_util.py: replaced unused variables in process_comments()
- instapy.py: added `security_codes` arg in constructor and `login_user()`
`process_comments()` now uses `user_name` for commenting a
target user; #5932
`comment_by_locations()` now has the same code for `process_comments()`
- login_util.py: Added random import due to login_user() feature with Two Factor
Authentication. `security_codes`, must be a list with codes
and InstaPy will chose only one element randomly.
Added new `def …

Problem: Added Two Factor Authentication feature, intended for protected

---

CHANGELOG.md
instapy/browser.py
instapy/commenters_util.py
instapy/instapy.py
instapy/login_util.py
instapy/relationship_tools.py
instapy/settings.py
instapy/story_util.py
instapy/util.py
instapy/xpath_compile.py

Hello all,
I created this PR to solve some issues with login session and other minor fixes regarding outdated xpaths,
I've been using this branch past week and everything goes well.
Thanks for considering my request, 
have a nice day.
`instapy/browser.py`: moved user_agent to general settings, now all code
uses the same agent definition
`instapy/commenters_util.py`: Added logger to `get_users_from_dialog()` to
trace actions
`instapy/instapy.py`: Added the Exception to the STDOUT when a failure
`instapy/login_util.py`: `login_user()` reordered to avoid stale elements or
timeouts due to the latest IG changes, id `SameSite` cookie. In a failure
with the cookie a new one will be created to avoid user interaction at
OS level.
In some regions a new question for saving cookies in the machine is …

Lloggin session detailed and minor fixes

---

docs/actions.md
docs/additional-information.md
docs/automate-instapy.md
docs/home.md
docs/instance-settings.md
docs/relationship-tools.md
docs/settings.md
docs/third-party-features.md
docusaurus/src/css/custom.css

Just a minor fix for google adsense.
Hope getting some more money which could be spend via Open Collective :)

Better Sponsoring

---

CHANGELOG.md
instapy/__init__.py
instapy/browser.py
instapy/comment_util.py
instapy/feed_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/pods_util.py
instapy/story_util.py
instapy/unfollow_util.py
instapy/util.py
instapy/xpath_compile.py

Hello all, 
Hope you are doing fine!
I created this PR to add a mechanism to comment a photo that has ben liked previously, and to solve some issues reported regarding some messages that could confuse InstaPy users.
Thanks in advance for considering this PR.
Happy new Year, wishing you health, wealth, and happiness in the New Year ahead.
Subject: PR comment photo already liked and minor fixes
Problem: This PR is intended to allow InstaPy users to comment a photo
that has been liked, it could be manual or automated interaction. Now
InstaPy can check the comments for a Photo and determine if InstaPy user
commented or not the same, if the Phote is not commented but liked the
bot will comment once. InstaPy will skip the Photo if it is liked and commented.
Pump 0.6.12 to 0.6.13 to sync pip …

PR comment photo already liked and minor fixes

---

CHANGELOG.md
instapy/login_util.py

adding delays after load cookie, permit instapy to have time for cookie login, without erase it, if is valid
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

adding delays after load cookie in login.util.py

---

CHANGELOG.md
docs/actions.md
instapy/instapy.py

This commit introduces a new feature I have found to be missing from InstaPy so far: Interacting with the likers from a given user's posts.
Personal IG account, works as expected

Introduce `interact_user_likers`

---

CHANGELOG.md
docs/actions.md
docs/additional-information.md
docs/settings.md
instapy/__init__.py
instapy/follow_util.py
instapy/like_util.py
instapy/relationship_tools.py
instapy/util.py

Hello all,
Could you help me to review this PR, I tried to include some minor fixes for some assertions that are confusing some InstaPy users. Basically, the changes are the following:
Bumped from 0.6.13 to 0.6.14, to propagate the new version to InstaPy-Docker
Added delays after `update_activity()` in `follow_util.py` and `util.py`, intended to reduce the STALE element messages
Added extra trace in `get_followers()`, to notify the error status when a user cannot be interacted; debuging purpose.
Fixed `additional-information.md`, removed extra info for `cron` configuration; there were duplicate values for same info.
Fixed `actions.md` and `settings.md` for indentation for examples.
thanks for considering my request.
Note:
Please include a summary of the change and which issue is fixed. …

Minor fixes, some delays for browser actions and traces.

---

CHANGELOG.md
instapy/browser.py
instapy/clarifai_util.py
instapy/comment_util.py
instapy/commenters_util.py
instapy/file_manager.py
instapy/follow_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/pods_util.py
instapy/print_log_writer.py
instapy/quota_supervisor.py
instapy/relationship_tools.py
instapy/settings.py
instapy/unfollow_util.py
instapy/util.py
instapy/xpath_compile.py
proxy_extension.py

Sometimes the following of users did not work and in addition if the follow was successful it could not be verified because of the follow button in the "promoted" users div.
Fixes #6200
Fixes #6205
Tested and working fine for me now

Fix user following

---

CHANGELOG.md
docs/settings.md
instapy/instapy.py
instapy/util.py

Adds skipping of public accounts
Implements #6215
Tested it and seems to work fine!

Add skipping of public profiles

---

README.md

- removed broken link to instapy.io in README.md

remove broken instapy.io link from Readme file

---

CHANGELOG.md
instapy/__init__.py
instapy/relationship_tools.py

Fixed #6417

---

.gitignore
CHANGELOG.md
docs/settings.md
instapy/__init__.py
instapy/clarifai_util.py
instapy/comment_util.py
instapy/commenters_util.py
instapy/feed_util.py
instapy/follow_util.py
instapy/instapy.py
instapy/like_util.py
instapy/login_util.py
instapy/relationship_tools.py
instapy/story_util.py
instapy/unfollow_util.py
instapy/util.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
#6352 
*is_private_profile() when sometimes NoneType is returned
- Added filter in `extract_text_from_element()` for non-username elements.
- Fixed `is_private_profile()` when 'NoneType' object is not subscriptable
- Fixed `find_element*()` to `find_element()`
- Functionality is the same, but now selenium 4 uses `find_element()`
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- [-] I have made corresponding changes to the documentation

PR - Fix `extract_text_from_element()`and `find_element*()` to `find_element()`

---

.github/workflows/tests.yaml

Signed-off-by: elulcao <elulcao@icloud.com>

Remove Python3.5 from test workflow

---

instapy/instapy.py
instapy/like_util.py
instapy/util.py
instapy/xpath_compile.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Updated Instagram xpaths. Added
