InstaPy/InstaPy

instapy/comment_util.py, instapy/like_util.py, instapy/unfollow_util.py
Instagram changes the class of elements for some users/locations.
I’ve changed the like, follow and comment references for XPATH, instead
of Class.
Also added coding header on comment_util for avoiding errors when user
comment contains special characters/accents.
=> Fixed like, comment and follow references

instapy/like_util.py
I've tested with multiple languages, resolutions, users and locations
and seems that the coreSpriteLikeHeart class never changes.
When the image is not liked yet, the class is coreSpriteLikeHeartOpen,
when the image is already liked the class changes to
coreSpriteLikeHeartFull.
This should fix the language/locale issue with the like function, but
the comment function must be reviewed.
=> Multilanguage Like

instapy/instapy.py, instapy/like_util.py
With the #33 I realized that there’s a JS variable that contains all
data that we need and that the UI of Instagram Web differs from users
(use_new_styles flag).
Changed the XPATH/DOM references for JS functions to retrieve the data,
independent of ‘use_new_styles’.
Also made a change on InstaPy.py that forces the Chrome to run with the
“en-US” location to avoid the Locale/Language problem with the like
button and the comment placeholder.
=> Make like_util work independent of 'use_new_styles' 

instapy/like_util.py
Instead of calling Selenium method Click, get the Class of the Like
Button and do a Click() with Javascript.
If there’s an element above the Like Button, Selenium doesn’t hit it
and throw an error, JS don’t.
=> Fix like when the "Get the App" bar is visible

instapy/like_util.py
Syntax error: Missing parentheses in call to 'print' in like_util.py, line 80
Coherency: Change double quotes to single quotes in like_util.py, line 80
=> Fix parentheses and quotes in like_util.py

instapy/like_util.py
Avoid going to the image poster profile page and back to the image if we are not filtering the likes by number of followers.
This is not about the logged in user (the one running the script). This is about the owner of the picture being liked.
=> Only get number of followers if actually needs to.

instapy/comment_util.py
Added an explicit wait on the comment_input element. If the element isn't found within 10 seconds then warn the user and continue without commenting. 
This may return sooner. It's just capped at 10 seconds to find the element. Hopefully this addresses some of the issues we've been having.
=> comment_util fixes

instapy/instapy.py
When client encoding not support some unicode characters, raises the error.
sample error:
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f6b2' in position
251: illegal multibyte sequence
=> Fixed an encoding issue when writing log

instapy/instapy.py
i've make a small change to improve selenium running more fast & smooth:
- managed_default_content_settings.images = 2: Disable images load, this setting can improve pageload & save bandwidth
- default_content_setting_values.notifications = 2: Disable notifications
- credentials_enable_service & password_manager_enabled = false: Ignore save password prompt from chrome
=> improve selenium settings

instapy/unfollow_util.py, instapy/util.py
This pull request fixes two problems with the unfollow feature
1. the path of the dialog box changes
2. the script did not unfollow if the first users were not in the pool because it didn't scroll
This closes #456 and closes #453
=> fix unfollow errors

instapy/instapy.py
Firefox Capabilities doesn't seem to make any difference at all in most of Firefox newer versions.
Furthermore, as seen in #473, it throws an error when used in the newest version.
=> Removing Firefox "Capabilities" as it seems useless in newer versions

docs/How_to_Raspberry.md
As seen in #473, the `tar` command was trying to extract an already extracted file if the user had previously extracted another driver.
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
=> Fixes the extract problem in How_to_Raspberry.md

instapy/instapy.py
It seems like in Python 2 math.ceil actually returns a float instead of int, which causes problems for the random.sample function.
This fixes the error mentioned in #509 by parsing the returned value to int.
=> Fix for the math.ceil problem #509

instapy/unfollow_util.py
Its a very nice a pull request it fixes the problem "can't multiply sequence by non-int of type 'float'" while adding the option for non integer sleeps.
There is no reason to force the sleep to be a integer. it also doesnt work on some operational sysmtem
=> Paunocu's fix the sleep ceil

instapy/instapy.py
As it is for "like_by_users", if a tag or a location has too few images the script should just "continue" iterating the array.
=> "Too few images" is not a good reason to abort

instapy/like_util.py
Change the h2 class attribute to match new class naming in instagram.com, as to mantain functionality of verification of a user's private status.
=> Fix is_private verification

README.md, docs/index.md, examples/example.py, instapy/clarifai_util.py, instapy/instapy.py, setup.py
Clarifai recently changed the way users could access their API (traditionally done with app_id and app_secret). Now they only provide an api_key and will deprecate the old way sometime towards end of 2017. 
This pull request removes app_id and app_secret from the API call and replaces it with api_key and updates the documentation. Clarifai's V2 API also only supports matching input photos against an existing model so that was updated in the clarifai_util.py file as well. 
Documentation was also updated.
=> Solution to #503

instapy/unfollow_util.py
The unfollow method is being sent `username` as a param but inside the method we're looking for `user_name` creating an error `('following_link error \n', "global name 'user_name' is not defined")`.
This bug was introduced today in https://github.com/timgrossmann/InstaPy/commit/a6f93227c4ea8cb5cae90b4523b021c632273d21
=> Fix following link

instapy/like_util.py
Following the idea from the pull request #589 we should get rid of the click triggered via execute_script.
I'm actually asking myself why we were getting the className from the xpath element and then using javascript to get it again by className to finally click on it 😆
=> Use send_keys on like buttons too

.dockerignore
Removed /requirements.txt from dockerignore or else the docker-compose.yml won't build. The pip install -r requirements.txt command fails when /requirements.txt is ignored.
- Even the COPY command will fail fstat because there is no /requirements.txt.
=> Removed /requirements.txt from dockerignore

docker-compose.yml, wait-for-selenium.sh
When I tried the `docker-compose up --build` command on ubuntu there were no problems. Then I tried this on arch linux and debian with less luck. 
_There were some problems._
**Problem 1:**
Random generated hostnames by docker-compose v3
The hostnames defined in the scripts were `http://selenium:4444` and many pullrequests suggest you should change it to the ip. Then I got myself thinking docker generates hostnames why bypass them to fix this issue? The problem with docker-compose is it behaves different on other operating systems. So then I looked to the hostnames in ubuntu and they were `selenium`. Then I saw the debian hostname this was completly off `instagramselenium_selenium_1`. 
TLDR;
The fix was very easy, we make now use of:
```
container_name: selenium
``` 
**Problem 2:**
The …
=> Fixed docker hostname on debian and arch and wait for service is loaded on port 4444

instapy/instapy.py
There are issues with docker and the maximizing of your chrome window:
https://github.com/SeleniumHQ/docker-selenium/issues/396
I am having these problems on Ubuntu and Debian and arch.
We are using the standalone version, so I suggest to remove it or set a default.
=> Removed maximze window this causes problems with docker

instapy/instapy.py
Was found via #713
* Also put multi-line if statement in parentheses to avoid using backslashs like the plague that they are (See PEP8). 
* A problem remains that __checked_img__ is an undefined name in this context.  It is defined as a local variable in several other functions/methods but it is not defined until 50 lines later in this one.
=> Fix typo in variable name: user_name --> username

instapy/unfollow_util.py
These issues shared the same exception message:
`element is not attached to the page document`
After looking into the function `follow_given_user` and move the line `browser.find_element_by_xpath(...)` below `sleep(10)` the issue gone away.
Also the xpath selection expression was: `"//*[contains(text(), 'Follow')]"`
which will also match "Following", therefore changed to `"//*[text()='Follow']"`
=> #402 #425 #336 fix selenium exception on follow button

.travis.yml
The owner of the this repo would need to go to https://travis-ci.org/profile and flip the repository switch __on__ to enable free automated flake8 testing of each pull request.
The output will look like: https://travis-ci.org/cclauss/itinerant-tester/builds/283213087
=> Use Travis CI to run flake8 tests on pull requests

instapy/feed_util.py
__selenium.common.exceptions.NoSuchElementException__ is an undefined name in this context but line 7 does define __NoSuchElementException__ by importing it from __selenium.common.exceptions__.  Undefined names can raise [NameError](https://docs.python.org/3/library/exceptions.html#NameError) at runtime.  Was found via #713
=> Fix undefined name found by flake8

instapy/instapy.py
#184 small bug fix, deletes white spaces in tags (like_by_tags) to prevent find for inexistent tags
=> 184_bug_fix

instapy/unfollow_util.py
//*[contains(text(), 'Follow')] matchs the "Following" word too, that means that if even we were already Following this profile, it would try to Follow it again, resulting in a unfollow action.
=> locate button xpath only if text is exactly the follow word

instapy/instapy.py, instapy/util.py
There is a problem on windows when we try to delete a temporary file. To fix this, the solution is ugly, needs extra win32 libs. I think it's a good idea for now to not provide this functionality to windows users.
=> Removes Record activity functionality for windows users

instapy/instapy.py, instapy/util.py
bug fix for #818 
Validation added before user interaction, so we don't need to interact if the user doesnt meets requirements
1. not in blacklist
2. not in dont_include
3. respecting upper followers count limit
4. respecting lower followers count limit
5. not interacting with private accounts
=> validate user before interact in interact_user_followers

README.md
In order to prevent unfollowing active users, enabled=True has to be used
=> Readme fix for set_unfollow_active_users

instapy/instapy.py
I tested it for 3/4 hours without **element no visible**.
(Tested on MacOS and Linux Debian)
When testing it, please remember to update InstaPy and chrome driver to latest version.
=> avoid setuid sandbox type

instapy/unfollow_util.py
I realized that after #1009 the scroll bottom method was not working correctly anymore. The dialog selection is now correct and hopefully more robust than the previous one.
=> Update for dialog selection in unfollow_util.py

README.md, instapy/instapy.py
Use `headless_browser=True` in the constructor to enable Headless
Chrome - executing your scripts without a Chrome window or GUI opening.
It’s all done in the CLI! Excellent for servers or running in the
background while consuming less CPU.
=> Implemented option to execute script with Headless Chrome in the InstaPy constructor

README.md
Most people just download the zip file and does not extract it. See #1176
This results in the error
```
Traceback (most recent call last):
File "quickstart.py", line 40, in <module>
session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7fec4bb66510>> ignored
```
=> Added the advice to unzip the chrome-driver

instapy/instapy.py
Either way, unfollow=False will not stop unfollowing inappropriate media owners. Actually, stopping unfollow in certain inappropriate medias is **vital**. Such as, i dont want to like #food pics but it should not unfollow everybody with that tag.
Or maybe, **much better**, there could be some improvement to unfollow tool, like if it gets certain amount of inappropriate tags in a media, it should do unfollow (e.g. very inappropriate).
=> Fix unfollow=False issue in "Like by Feed" def

README.md, instapy/instapy.py
I had the same issue mentioned in #894 and did not get it to work, so I basically copied the interact parts from like_by_feed and added them to like_by_tags. 
But the like_by_user called in like_by_tags didn't seem to work without a proper like_by_followers_upper_limit (because of util.py:31 with like_by_followers_upper_limit set to 0). So i figured the most simple way is to change the default value of like_by_followers_upper_limit to 90000. I don't really see a reason why it should make any problems, but i'm not 100% sure that's why i mentioned it.
=> added interact option to like_by_tags #894

instapy/instapy.py
I don't believe there was an issue for this, but I encountered an error where the log messages were duplicating themselves multiple times. The issue had to do with instantiating the `logging.getLogger(__name__)` singleton multiple times.
I was using the [retrying library](https://github.com/rholder/retrying) in my quickstart file as follows:
```python
@retry(stop_max_attempt_number=20)
def main():
session = InstaPy(username=insta_username, password=insta_password)
...
```
However, because I would re-instantiate the `InstaPy` object upon each retry, it would add additional loggers to the existing logging instance. This resulted in duplicate output.
I have updated the logging setup in the instapy file to avoid this issue (by retrieving an existing logger from a cache if one has already been …
=> Update logging instantiation

instapy/instapy.py
I have test it locally, it all working fine. Please have someone else take a look and test it as well.
`sys.meta_path is None, Python is likely shutting down` error is preventing the Chromedriver close properly.
=> fix the sys.meta_path is None, Python is likely shutting down error

instapy/instapy.py
`follow_by_tags` calls were failing since `follow_user` was called with 6, instead of 7 arguments, as `self.logfolder` was missing.
=> missing self.logfolder argument to follow_user

instapy/unfollow_util.py
a chrome "element not found" error happens -- the specific Python exception mentions a KeyError on the 'after' key. the commit in this PR fixes this issue.
this relates to issue #1242
=> fixes an issue when running unfollow_users with onlyNotFollowMe

instapy/instapy.py
Fixes https://github.com/timgrossmann/InstaPy/issues/1394
This passes the new required logfolder argument when `like_image` is called
=> Add required argument logfolder to like_image

instapy/unfollow_util.py
Remove Requested follow from users that didn't approve follow request. 
* Instagram limit 7,500 of following users. include following requests. means that if you have many unapproved requests it's can block you from follow new accounts. there is no way to go back and delete the requests. Instagram don't provide feature to see all outgoing requests therefore this feature is highly important.
=> Remove Requested follow

README.md, instapy/instapy.py, instapy/like_util.py, instapy/print_log_writer.py, instapy/unfollow_util.py, instapy/util.py
As of @underclass [issued](https://github.com/timgrossmann/InstaPy/issues/1330)
to `unfollow_users` feature, in order to unfollow users **_after_** following them certain amount of time..
```python
unfollow_users (amount=10,
onlyInstapyFollowed=True, onlyInstapyMethod='FIFO',
sleep_delay=600,                   
onlyNotFollowMe=False,
unfollow_after=24*60*60)  #here, will unfollow every single user
#after following at least a day
```
_Time counts uniquely for every single user, after it is followed by InstaPy.._
**Actually**, it can be `unfollow_after=500` (will unfollow users if **500 seconds** of follow time passes), but
having it **`hours*minutes*seconds`** **is easier** than big numbers, such as `168*60*60` equals to a week (in other words `604800` seconds)
[]      []      []       [] …
=> Added unfollow_after arg to unfollow_users to Delayed Unfollow

.gitignore, instapy/instapy.py, instapy/login_util.py, instapy/settings.py, quickstart.py, tests/test_instapy.py
Removed the import condition for clarify which causes an exception. Fixes #1579 
Moved the session creation outside try-except to prevent error for `session is undefined` and added printing of the exception to get better stacktraces in issues.
Made the paths in settings relative to settings path, otherwise exception if ran from different directory. Changed browser_location as it points to the chromedriver specifically. Ref #1627 
Asserting username and passwords to prevent `None type errors`
=> Removed unnecessary import condition

quickstart.py
Relates  #1692 
The single line of the error is not helpful, rather print the whole stacktrace.
=> Provide full traceback on exception in quickstart

instapy/instapy.py
Ref #1550 
The traceback for the exception on session end is not necessary, as it is the not the cause; it's just a cleanup failing.
=> Handle exception on session during end

docs/How_To_DO_Ubuntu_on_Digital_Ocean.md
I tried to setup InstaPy on cloud server following the instructions on docs, and there was an error 
> ImportError: sys.meta_path is None, Python is likely shutting down
So looking through the traceback I've found this 
> InstaPyError: chromedriver 2.34 is not supported, expects 2.36+
Updating chromedriver solved the problem
=> updates chrome driver version (2.36)

quickstart.py
I've noticed that `traceback` fails with selenium errors :(
But, can just raise and have same effect...
Also, create file to help us debug issues with elements not found: ref #1621
=> Additionally provide html for no element found errors

instapy/unfollow_util.py
If read from file list of names they won't be stripped and that causes in error when user_name comes with "\n"
=> fixed bug with username not stripped before xpath search

instapy/like_util.py
like_util is interpreting specific characters as byte code instead of string. Added str() cast to both items to temporarily fix this. The root problem should potentially be fixed, but for now this commit will prevent issues and allow root problem to be identified.
=> This commit fixes issue #1814

instapy/like_util.py
If any of the words that are given in this list appear in the description, we want to interact with the post instead of passing it as inappropriate
=> Fix Ignore if contains

instapy/instapy.py, instapy/util.py
Fixes issue #1819 .
The issue is that it detects only the first 20 users that liked a post. This pull requests implements code by @uluQulu that contains a scroller to go through the list of likes. 
Note: Video likes do not show up on a desktop and won't be found by this function.
Boundary controls the amount of likes that should be looked at so that users can control how long they want the function to take.
if Bounday = 0 then grab only visible names as the default
if Boundary = None then grab all the usernames that liked a photo
if Boundary = xx then grab xx amount of likers starting from the top.
=> Detect likers past 20 on posts by scrolling

docker_conf/alpine/Dockerfile
In preparation for deploying InstaPy in Docker Swarm, I created an additional Dockerfile using Alpine instead of Python base image, because:
1. The image can be auto-built using docker hub, making it quick to integrate into swarm
2. The alpine image is 329MB, whereas the python image is 807MB
I'll send another PR for a docker-compose file which will actually _use_ the alpine image, this is just a preparatory contribution.
=> Add docker alpine image

instapy/unfollow_util.py
Instagram API changes sintax in query for getting followers and following for a given user and also set a maximum of 50 results per query.
=> Instagram API updated graphic query

instapy/like_util.py
Qulu fella told me to do a PR, its my first time hope im doing it right 
potency_ratio=None causes error when used with interact_with_user [#1910](https://github.com/timgrossmann/InstaPy/issues/1910)
```
Traceback (most recent call last):
File "quickstart.py", line 45, in <module>
session.interact_by_users(users[:2], amount=1)
File "C:\Users\marti\OneDrive\Proj\InstaPy-master\instapy\instapy.py", line 1307, in interact_by_users
self.logger)
File "C:\Users\marti\OneDrive\Proj\InstaPy-master\instapy\like_util.py", line 551, in check_link
if potency_ratio < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
=> Update like_util.py, error when potency_ratio = None

instapy/unfollow_util.py
As it might lead to an exception:
"StaleElementReferenceException"
according to :
https://stackoverflow.com/questions/16166261/selenium-webdriver-how-to-resolve-stale-element-reference-exception
1. An element that is found on a web page referenced as a WebElement in WebDriver then the DOM changes
(probably due to JavaScript functions) that WebElement goes stale.
2. The element has been deleted entirely.
=> remove sleep between finding element and using it

instapy/instapy.py, instapy/like_util.py, instapy/unfollow_util.py
_`like_by_users` is prob my fav feature to have fun sometimes liking bunch of pics but it has an unwanted behavior should be changed.._
**Currently**, `check_link` utility is visiting the user's profile page in every posts in order to find followers & following counts.
_And it does **the same** for the feature of `like_by_users` where, from the same user(s) it views bunch of posts and visits profile page in each post to get those values..._
**Now** when a user's relationship bounds **is matched** for once, it **will not be checked** in the next posts of that same user again.
**Similarly**, if a user's relationship bounds **is not matched** with the range desired, then it **will simply skip** that user _without seeing further posts_.
>This applies to all features using `like_by_users` …
=> Revised `like_by_users` feature to speed up the process

instapy/util.py
Updated the `xpath` for followers count which Instagram has changed.
It should solve the `get_number_of_posts()` function
Linked issue: #2145
=> Fixed follow commenters of photos of users

instapy/instapy.py
the NoSuchElementException exception cannot decode to utf8.
=> update like by locations

instapy/print_log_writer.py, instapy/unfollow_util.py
Thanks to @ximhotep
Accounts removed by IG aren't being removed from followedpool.csv causing unfollow to iterate through those accounts every cycle. Recommended adding the two additional calls to delete_line_from_file to remove users from followedpool.csv
** This is a diffrent fix based on the return following is False, so we will go to the else.
----------------
Added also the cancellation of ctrl+c when updating a file
=> Updated Unfollow to remove unfollowed or removed IG accounts from followedpool.csv; cancellation of ctrl+c when updating a file

instapy/instapy.py
Due to a DOM modification by instagram , the username of the user to follow/commenting cannot be retrived.
please see my issue here : https://github.com/timgrossmann/InstaPy/issues/2539
=> update getting username

instapy/database_engine.py, instapy/settings.py, instapy/util.py
Hey guys, I've included a few issues from people after #2563 and the solutions for them.  
**1**. I didn't know that `git` doesn't like empty folders where it removed the **db** folder after **instapy.db** pre-loaded file was removed.  
+ Added a smart layer to make the **path** in the given or default database location **if not exists**  
>  Other options are adding some small info file so that it is not empty to be removed by `git` OR add that file to `.gitkeep`, etc. But these options will work only for default **db** folder, so I chose a solution which will also work for custom locations off `Settings` class, too.
_Affected users **were** WHO cloned/downloaded the repo after #2563. But e.g. users who just pulled #2563 as an update could not face that issue, cos `git` keeps that **db** …
=> Fixes for the #2563

instapy/comment_util.py
I found that because of `raise`, the process has not reached `return True, 'Verification failure'`.
So, I deleted `raise`.
If you prefer `raise`, I will rewrite it like that.
=> able to return True

instapy/unfollow_util.py
Highlighted, troubleshooted and solved at  #2589.
Shortly, I will say that it is a runtime error happened for some old python versions (_like 2.7_) where **slicing** the elements of a fetched _sqlite3_ `Row` _list_ is not yet implemented.  
Please see #2589 for more technical details.
>Earlier I've mostly used **replit** to test some little code off py2 portability but this time having a DB situation made me finally install python `2` on local system 😀 and now looking forward to install a good _tester_.   
_Special thanks to @bianpratama to post a good feedback in order to understand the cause of this **little** error._
Cheers 😁
=> Fix slicing issue off #2563 (hit py2)

instapy/database_engine.py
Having my **InstaPy** not affected any bit by that, it took lots of time thinking about the heart of this issue,
```erlang
Heeh! Error occured while getting a DB profile for 'None':
b'NOT NULL constraint failed: profiles.name'
```
And **solved** it 🤝🏼 with the invaluable collaboration and help of @Mehran 💪🏼 WHERE shared the VPS console to troubleshoot the issue and funnily in the first attempt found the cause of it!  
>It's the problem issued in a few **Issues** and discussed in #2578 thread.
**The thing is** before _python_ `3.6`, dictionary order was arbitrary. It means that the dictionaries don't have an order for those versions.  
------------------------------------------------------------------------------------------------------------
```erlang
profile = {"id":None, "name":None} …
```
=> Fix for the most nasty bug off #2563

instapy/like_util.py, instapy/util.py
Updated how we check if the user is private because it took 25 seconds with the find_element_by_xpath function.
It takes less than a second with this edit.
Work by @mehdichekori @sionking
=> Faster way to check if user is private

instapy/like_util.py, instapy/unfollow_util.py
It popped up last weeks and was issued in a few **Issues** until solved at https://github.com/timgrossmann/InstaPy/issues/2555#issuecomment-410475845.
If you read that comment in #2555 you will understand why I did not include it in a PR yet.
Basically, I wanted to understand how that `quick_username` variable can be empty.
But having no any continuous feedback I still am unsure about it.
Yet, the change included in this PR is still operational and harmless and will prevent possible crashes at that point.
If you want to understand why it may return an empty list, have a read this comment by the author of previously called `follow_through_dialog` (@BernardoGO?).
There is a comment line in `dialog_username_extractor` of **unfollow_util.py** file which is used to extract the `quick_username` …
=> Prevent indexing error once `quick_username` comes out empty and other fix

instapy/print_log_writer.py, instapy/unfollow_util.py, instapy/util.py, quickstart.py
I have thought of implement this for awhile now,  Especially after got more than 100+ user that stuck in my following list that not able to unfollow (most likely they have changed their username)
Finally I was able to implement it after I got back from a long business trip. 
here are the changes:
Inside the `USERNAME_followedPool.csv` instead of only logging the username as it was (today) e.g.
```
2018-08-21 16:04 ~ javaabcdefg
```
It now become something like this 
```
2018-08-21 16:04 ~ javaabcdefg ~ 1234567890
```
**During unfollow procedure, if the instapy not able to load the following user profile by the `name` it will try use the `userid` that was logged to get to the profile page.** Which means, whatever the username change into, we should always able to find the user and to …
=> Log the userid when following other users

docs/How_to_Windows.md
Seems like the windows install file is not working correctly, therefore the Guide with the "simple" setup leads to a lot of people being confused
=> Remove "simple setup" from windows setup

instapy/instapy.py
Although there is already [PR to fix such issue](https://github.com/timgrossmann/InstaPy/pull/2711) (and I am sorry for duplicate, initially I just fixed it for myself), it's incomplete and I think that changing port argument type from int to string is not a correct way to solve the problem (it may require changes for existing projects).
=> Fix: proxy_port default value is None instead of 0

examples/firefox_patcher.py, instapy/monkey_patcher.py
I'm use InstaPy in raspberry pi and cannot move to newer version of firefox.
I found some bug about MoveTargetOutOfBound if use method move_to_element in ActionChain class
in it like bug in selenium.
bug suggest to fix with manual move to element with alternative way and to something with it. 
I use
Raspberry pi 2
Selenium: 3.4.3
Geckodriver: 0.17.0
Firefox-esr: 52.9.0esr-1~deb9u1
Relate issue: #596 #803 #2591
Solution:
I wrote patch to move to target element before call real method.
I don't call patch in part of InstaPy code to prevent people who use old selenium or geckodrive but I also add example feel free to use.
=> Fix MoveTargetOutOfBoundsException on Legacy Firefox

instapy/unfollow_util.py
Problem is when shuffling COS `random.shuffle` cannot work with `dict_keys` objects
For example in my python 3,
```python
zx = {1:2, 3:4}
sl = zx.keys()   # sl is dict_keys([1, 3])
ld = list(zx.keys())   # ld is [1,3]
```
Hint: There is no problem while iterating over `dict_keys` objetcs
_It happened specially after I refactored `set_automated_followed_pool`_
Still wonders how I did not notice bug this before 🤔 until running a test for #2882
------
Cheers 😁
-----
=> Bug Fix: make sure `unfollow_list` is always a list (rather than a `dict_keys` object)

instapy/unfollow_util.py
Reminded by @sionking at #2888 
It was,
```python
if follow_button.is_displayed():
else:
```
Now,
```python
if follow_button.is_displayed():
else:
```
It is just the follow verification block indented back (_4 spaces_).
While I merged @sionking's PR, I revised that verification block and attached to the general follow engine- `follow_user()` AND there, somehow did not see the first follow block 😂 at that time.
-----
Cheers 😁
--------
=> Revise indentation at follow verification block to support both conditions

instapy/commenters_util.py, instapy/unfollow_util.py
Hey guys
Here is the reasons for this PR,
+ 1st commit - https://github.com/timgrossmann/InstaPy/issues/2882#issuecomment-420370821
Well to say more words,
it happened cos the button accomplished its job after inconsistent time delays and there is a verification block which was misbehaving.
Now, `explicit_wait()` waits for enough time [default- 66 seconds] and releases back as the button has accomplished its job.
In case of it cannot accomplish its  job - it cannot unfollow; There it will timeout after the pre-defined delay [default- 66 seconds] and will reload page and try the same step again and in case of the second timeout, it will break the loop cos it is a sign of shadow ban.
>The usage of `explicit_wait()` is amazing 👈🏼 stability + performance + simplicity + speed
+ 2nd commit - …
=> Fix issues out of inconsistent delays while after clicking the Unfollow button from the pop up dialog AND some others

instapy/instapy.py, instapy/util.py
When interaction with a user start we shall:
* do at least one action follow/like/like+comment if validation is pass
* dont follow if one image in posts fail in check_image (optional* default is True)
* roll decision again in second post and beyond.
* fix: don't try to follow (again) when amount of posts is more than 1.
* save time by not checking the data bases over and over (static decisions)
Please verify logic.
=> Add decision making in interaction

instapy/comment_util.py, instapy/commenters_util.py, instapy/feed_util.py, instapy/like_util.py, instapy/login_util.py, instapy/print_log_writer.py, instapy/relationship_tools.py, instapy/settings.py, instapy/unfollow_util.py, instapy/util.py
Earlier there were no URGENT reason to have _server calls_ (_or other actions_) updated cos those data WAS NOT used anywhere except by the people who was reading the **instapy.db** file to analyze record activity statistics.
But after Quota Supervisor came out, now every action counts.
That's why _server calls_ must be recorded PROPERLY after each request to the server [mostly by `GET` navigation method, page _reload_, _click_ and _scroll_ actions]
Having known that matter I have added all of the missing [required] lines of `update_activity()` which is updating _server calls_ record in the local DB to be used with QS and etc.
------
While doing the job mentioned above, I also did other visual changes to increase readability, etc.
Also,
+ Replaced a few direct `GET` method navigation to …
=> Add missing `update_activity()` lines to update server calls AND lots of Visual changes & Simplifications

README.md, instapy/instapy.py, instapy/util.py, quickstart_templates/like_by_tag_interact_unfollow.py
```python
session.set_skip_users(skip_private=True,
private_percentage=100,
skip_no_profile_pic=False,
no_profile_pic_percentage=100,
skip_business=False,
business_percentage=100,
skip_business_categories=[],
dont_skip_business_categories=[])
```
**This is done by default**
```python
session.set_skip_users(skip_private=True,
private_percentage=100)
```
Will skip users that have private account, even if are followed by running account.
You can set a percentage of skipping:
_private_percentage_= 100 always skip private users
_private_percentage_= 0 never skip private users (so set skip_private=False)
```python
session.set_skip_users(skip_private=True,
skip_no_profile_pic=True,
no_profile_pic_percentage=100)
```
Will skip users that haven't uploaded yet a profile picture
You can set a …
=> Skip Private/Business/No Profile Pic, Min/Max posts

README.md, instapy/instapy.py, instapy/login_util.py
I run a lot of accounts with instapy, and sometimes user didn't add their email to instagram, or they'd prefer phone number over email so I thought It'd be really great to give people an choice for bypass suspicious login attempt.
=> Add Bypass suspicious login attempt option for mobile phone 

instapy/unfollow_util.py
When follower list is scrolled directly to the bottom, suggestions are showed and follower list is not being loaded. Scroll to the end of list first to initiate the first load which hides the suggestion list.
=> Fix to "Failed to load desired amount of users"

instapy/instapy.py
Hey,
I wanted to propose making remote selenium driver injectable. This would allow providing pre-configured driver instance to InstaPy, which now is impossible. 
My use-case is running several sessions in parallel from Celery workers which fails with current configuration of remote Selenium session.
Let me know what you think, sorry for not making an issue first to discuss it but it's such a small change that I just went ahead and did it 😄
=> [Proposition] Add option to inject selenium driver for remote session

CHANGELOG.md, instapy/like_util.py
I generally don't do what others do but I wrote this cos other fixes looked so complex and harder to maintain.
After IG has introduced comment liking capability to its Web interface, now comments also has the area-label of `_Like_' which made problem.
It searched for all of the elements with the area-label of '_Like_' and it found both comment's like button and a post like button elements.
And in some posts there are no comments [to be like] so it worked in those posts cos that found element was the exact like button of the post.
And I have also analyzed this fix's state.
E.g.,
```erlang
like_xpath = "//section/span/button/span[@aria-label='Like']"
```
`section/span/button` refers to the like button of the post
`div/span/button` will refer to the like button(s) of the comment(s)
_And with …
=> Fix Invalid Like Element issue.

CHANGELOG.md, README.md, instapy/clarifai_util.py, instapy/instapy.py
Updated a couple of the functions in clarifai_util.py to add support for checking videos via the Clarifai API. Since workflows do not take video inputs and only a few of the models accept video inputs, in many cases the keyframe will still be checked for content. 
Also fixed blocks for compiling the list of concepts for the Celebrity and Demographics models.
=> Support for Checking Video Inputs with Clarifai

CHANGELOG.md, instapy/instapy.py, instapy/like_util.py, instapy/unfollow_util.py
I also think we shall maintain names: 'person' for target user and 'username' for our running user.
=> verify private users in get_links_for_username; small fixes

.github/stale.yml
Based on @converge idea about having a bot that closes old and stale issues to get a better overview on the still remaining issues and especially the most recent ones that haven't been fixed, this PR introduces a bot that marks issues where there was no activity in the last 30 days. After 7 more days the issue will then be closed.
Any comments or requests about the time till stale and time till close?
Thank you for this very good idea, @converge! 👍 
> P.S. we really need to get that PEP change working with the pipeline...
=> Add issue bot for automatic closing of stale issues

.github/stale.yml
The way the bot crates the stale text in the issues is not formatted correctly.
Changed it to be in a new line. Uses the citation the right way now,
=> add line break to use citation in markdown

CHANGELOG.md, README.md, instapy/like_util.py
Added the location (if any) of an image to the image_text in the check_link method in like_util.py, so the mandatory words check also checks the location. 
This is useful when targeting images with a certain hashtag that where taking in a certain location. Sometimes the user tags the location, sometimes the location is in the description. Both should be included.
=> Added location to image description

README.md, instapy/like_util.py
Change mandatory_words to ANY instead of ALL under check_link def. Mandatory words for commenting is already using ANY so maybe this was a typo.
Mandatory Words ALL might be useful on rare occasions but it is very restrictive and use quite a lot of connections. 
**Edit: if you want to keep both ANY and ALL, we can introduce any_mandatory_words and all_mandatory_words (for commenting and liking). Let me know!**
=> Check_link > Switch mandatory_words to ANY instead of ALL

instapy/unfollow_util.py
This PR fix the issue with unfollow feature.
```python
session.unfollow_users(amount=5,
allFollowing=True,
style="LIFO",
sleep_delay=600)
```
I had two options:
1. dialog_address = "//div[3]/div/div/div[2]"
2. dialog_address = "//button[text()='Followers' or text()='Following']/../../../../../.."
I choosed the first option one because it's easier to understand
=> unfollow_fix_converge

CHANGELOG.md, README.md, instapy/instapy.py, instapy/like_util.py
https://github.com/timgrossmann/InstaPy/pull/3434 
Updated to latest master.
```python
session.set_mandatory_language(enabled=True, character_set='LATIN')
```
`.set_mandatory_language` restrict the interactions, liking and following if any character of the description is outside of the character set selected (the location is not included and non-alphabetic characters are ignored). For example if you choose `LATIN`, any character in Cyrillic will flag the post as inappropriate.
* Available character sets: `LATIN`,  `GREEK`, `CYRILLIC`, `ARABIC`, `HEBREW`, `CJK`, `HANGUL`, `HIRAGANA`, `KATAKANA` and `THAI`
=> New feature: Mandatory Language (updated to latest master)

instapy/instapy.py, instapy/relationship_tools.py, instapy/settings.py, instapy/unfollow_util.py, instapy/util.py
Fix for unable to locate element "pre" in firefox browser and some minor PEP8 stuff.
When unfollowing users who had changed their names or had their accounts banned/removed in some way. Firefox encountered issues, this was due to the way it interpreted endpoint data, kudos to gitpatrickhub on issue #3444 for figuring this out. 
Edit: Just a note, upon further testing this only fixes it if the user has changed their name. it doesn't fix it if their account is deleted/removed or banned. Still looking for a fix for that.
Edit 2: Came up with a temporary solution for the above. Fix is implemented. This is ready to merge.
=> Firefox unfollow fix

instapy/unfollow_util.py
Prevents crashing when unfollowing fails for a certain user
Should provide a workaround for
#3602
#3523
=> Catch exceptions for unfollow_user inside loop

instapy/login_util.py
Sometimes the screen is smaller than the Instagram page, and the Login button wont be visible. ActionChains works looking for elements visible on viewport:
```python
(ActionChains(browser)
.move_to_element(login_elem)
.click()
.perform())
```
throws this exception if the Login link isn't visible on viewport:
```selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (901.4916915893555, 640) is out of bounds of viewport width (1280) and height (638)```
(Login button isn't visible)
--
The fix is click the link using the click() function.
=> #3656 (bug fix) change the way the login link is clicked

instapy/browser.py
Fix for non-authenticated proxies in chrome headless browser as mentioned in issue #3676.
Credits to @patacalas for pointing out the solution.
=> Proxy Fix For Headless Chrome

requirements.txt
- Fixes 
Remediation
Upgrade pyyaml to version 4.2b1 or later. For example:
pyyaml>=4.2b1
Always verify the validity and compatibility of suggestions with your codebase.
Details
CVE-2017-18342 More information
high severity
Vulnerable versions: < 4.2b1
Patched version: 4.2b1
In PyYAML before 4.1, the yaml.load() API could execute arbitrary code. In other words, yaml.safe_load is not used.
=> resolve security warning with new pyyaml version

requirements.txt
I made a fault with updating the requirement to get rid of the security warning with pyyaml.
4.2b1 is only a pre-release which makes it "more difficult" to install and fail with the new pip install instapy that will be introduced in #3722 
> Please note that this might introduce a "security warning" for this dependency. Will be fixed once 4.2b1 is released as stable
=> revert pyyaml requirement back to stable release

.gitignore, CHANGELOG.md, docker_conf/python/Dockerfile
Hello all,
I am running `InstaPy` with `Docker` and a best practice when creating Docker containers is keeping the size of the final image to the minimum possible. For a number of reasons including:
- Disk on space
- Reducing attack surface
- Upload time (if so)
- Performance (for old Docker version)
So, I rewrite `./docker_conf/python/Dockerfile` to reduce by half the size the final image from `1.34GB` to `512MB`. I'm pretty sure there is still few optimization possible and the size might be lowered, but it's a first step.
More generally regarding Docker, I'm pretty sure we can do some cleaning in the configuration:
- I also think it could be possible to reduce the size of `selenium` image (which is around `1GB` too) but I haven't already look at it.
- Cleaning `docker-*.yml` files: it's …
=> Optimizing Dockerfile for smaller docker image

README.md
There was a missing , between the parameters
=> Fix wrong syntax in set_quota_supervisor examples

CHANGELOG.md, instapy/commenters_util.py, instapy/relationship_tools.py, instapy/settings.py, instapy/util.py
I wanted to solve this issue after reading @sionking said that feature does not work anymore.
He wanted [proposed] to roughly apply the steps in the newly fixed `likers_from_photo()` function inside this feature- `get_active_users()` at #3764.
But `get_active_users()` function is not as simple as `likers_from_photo()` since `get_active_users()` is written to behave smartly.
E.g. I remember, I made it realize when it hits the bottom of the dialog box and stop scrolling at that point so that no any extra server call would be sent.
That was the main reason I solved it - to save `get_active_users()` from possible loss 😎
---
Also, now `set_dont_unfollow_active_users()` feature also has a Progress Tracker support.
Each commit made is unique with its specific explanation.
Please, read commit …
=> Fix `set_dont_unfollow_active_users()` feature completely

README.md
I commitet it directly in the master branch this time @timgrossmann 😁
Again only a small change like the thing with the commas. (It's still only fixed in dev 😝)
=> Fix inconsistent use of spaces before parameters

README.md, instapy/instapy.py, instapy/util.py, quickstart.py
<p align="center">
<p>
Thanks to @RuiFerreira#9357 from our _Discord_ server for the idea of parsing CLI args after what I've decided to share the solution with the community 🎊
And special thanks to @timgrossmann for design decisions.
I encourage you to view the changes at Readme - [Pass arguments by CLI](https://github.com/uluQulu/InstaPy/tree/dev#pass-arguments-by-cli) which explains _almost_ everything I can say.
One of the good news is it is implemented to be **fully flexible** for several use cases user can produce.
<br />
By default, it can parse 10 formal arguments of the _InstaPy_ constructor - [Currently these flags are supported](https://github.com/uluQulu/InstaPy/tree/dev#currently-these-flags-are-supported).
To get the list of available commands, you can type,
```erlang
python …
```
=> Pass arguments by CLI

CHANGELOG.md, instapy/file_manager.py
Accoring to #3920 people have issues when using their own chromedriver, since they fail on importing instapy-chromedriver package.
I don't know why this happens, since when installing instapy on Pi, it should also install the chromedriver package. The chromedriver might be the wrong version but it should still install the package.
Well but it still happens so user have to uncomment the import for instapy-chromedriver when using their own chromedriver.  
I just moved the import down where I use the Path so if you put your own chromedriver in the assets folder, it won't even try to import the one from the package.
=> Only import instapy-chromedriver when necessary

CHANGELOG.md, instapy/unfollow_util.py
as all user names in instagram are always lower case, to avoid user errors providing uppercase letters adding  .lower()
=> avoid user errors providing user names with caps

instapy/instapy.py
By submitting this pull request I acknowledge that I have read and agree to the code of conduct for this project.
This Pull Request addresses the following issue:
When `like_by_tags` is used with `set_do_follow` enabled, the user is followed in the `like_by_tags` method as well as in the `like_by_users` method which is called by `like_by_tags` to interact with the user.
This also causes the `set_do_follow` percentage setting to be actually double what is specified since the chance that the user gets followed is calculated twice once in `like_by_tags` and again in `like_by_users`
This PR fixes the issue by implementing a snippet of code already available in `instapy.py` to temporarily turn off the following for the interaction and then reverting the setting after the interaction.
=> Temporarily turn off follow for like_by_tags interaction

CHANGELOG.md, instapy/util.py
TBH I'm not sure that this have ever caused issues, but I think it might be related to the bot sometimes following users that do not match `relationship_ratio`. At most (or all) such cases the bot followed accounts with zero followers/following numbers.
Anyway, I think it is better to defend against division by zero.
Oh, and I also removed some trailing white space.
=> Prevent division by zero in validate_username

CHANGELOG.md, instapy/instapy.py
Expose the `threaded_session` parameter on `close_browser()` when calling  `Instapy.end()` method so that asynchronous tasks (Celery) work fine by setting that parameter to `True`.
=> Expose `threaded_session`

CHANGELOG.md, instapy/__init__.py, instapy/login_util.py
I've seen the login button text different in some occasions during past hour, so Instagram is probably doing an A/B test that can affect new logins without a previous cookie. The solution shall be as follow:
- Detect an alternative 'Log In' button if the regular 'Log in' is not found.
Needs to be tested and probably needs to be in a try catch statement, I currently cannot run my own code due my folder structure explained here https://github.com/timgrossmann/InstaPy/issues/4065
=> Solution for the 'Log in' text error due an A/B test

.gitignore, instapy/login_util.py
Currently the Instagram is having issue, my account is keep trying to login and can't find the "Login" element, instead of blow up with NoSuchElementException, add additional try catch along with return False to exit it gracefully. 
Also add gitignore to ignore all the *.db SQLite files.
=> Add additional exception cath

CHANGELOG.md, instapy/unfollow_util.py
Fixed "Failed to load desired amount of users" when trying to read long follower lists (users with hunders of thousands followers) that takes too long to load
=> Add sleep to wait for follower list to load

CHANGELOG.md, instapy/instapy.py
Fix an issue that if there is no smarthash tag the Instapy will blow up with UnboundLocalError
```
Traceback (most recent call last):
File "quickstart.py", line 22, in <module>
session.like_by_tags(amount=10, use_smart_hashtags=True)
File "/Users/congchencai/Documents/InstaPy/instapy/instapy.py", line 1885, in like_by_tags
self.logger.info('Tag: {}'.format(tag.encode('utf-8')))
UnboundLocalError: local variable 'tag' referenced before assignment
```
TBH, not sure how it ever worked, as the `tag` wasn't even in the for loop.
=> fix issue with smarthashtag returns no results

CHANGELOG.md, DOCUMENTATION.md, instapy/__init__.py, instapy/instapy.py, instapy/util.py
If you experience issue with multiple accounts Instapy.db lockup. You can add the following flag
`-sdb` when running in Command line
or 
To do this simply pass the `split_db=True` parameter in the InstaPy constructor like so:
```python
session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=False,
split_db=True,
multi_logs=True)
```
=>  split sq lite db by username

README.md
Opencollective should not display regular backers as Sponsors. 
Only monthly donators should be displayed as Sponsors, the rest as backers.
Removed the link for automatic retrieval of the Sponsors, they will be added manually.
=> remove backer from sponsors

CHANGELOG.md, instapy/__init__.py, instapy/instapy.py
Let's not punish the whole pods run for one bad data case.
=> catch exception for each post separately

instapy/instapy.py, instapy/like_util.py
This PR adds an additional check for blocking likes.
When receiving a ban on likes, the script continues to put likes. But if you refresh the page you can see that it is missing. If you liked the post in the application, you can see the blocking alert.
My suggestion is to check for a ban after every 10 liked image. That is, after putting a like, refresh the page and check if it is.
Sorry for my bad english. =)
=> added an additional check for blocking likes

instapy/instapy.py
Comparison using 'is' when equivalence is not the same as identity
When you compare two values using the is or is not operator, it is the object identities of the two values that is tested rather than their equality. If the class of either of the values in the comparison redefines equality then the is operator may return False even though the objects compare as equal. Equality is defined by the __eq__ or, in Python2, __cmp__ method. To compare two objects for equality, use the == or != operator instead.
=> Comparison using is when operands support __eq__

CHANGELOG.md, instapy/instapy.py
Assigning a variable to itself is useless and very likely indicates an error in the code.
Assigning a variable to itself is redundant and often an indication of a mistake in the code.
=> Remove redundant assignment by correting logic

CHANGELOG.md
This change fixes verifying mandatory words when the script can not get post description nor get comments, and also fix commenting when there is zero comments on post.
Fix issue: #4444
=> fix issue when verifying mandatory words (issue #4444)

DOCUMENTATION.md
The `from instapy import Settings` is required when you are using Settings methods.
=> Added import Settings

CHANGELOG.md, instapy/__init__.py, instapy/util.py
There is a fix for two more use cases related to #4518  PR and fixes #4517  issue. Also referencing #4520 because that PR tries to fix this same issue.
At the moment the script has been runing with a cron for 4 days without any errors.
Before the fix the script was breaking after the emulate follows session with the basic_follow_unfollow_activity.py quickstart template.
=> Fix for session.get_relationship_counts() broken behavior

CHANGELOG.md, instapy/__init__.py, instapy/util.py
Hey, this should fix `get_action_delay` bug #4540, returning default values even after updating values with `set_action_delays`.
Not sure whether to set merge into master or dev.
EDIT:
Hey this was just a one-liner change.
On master there is a bug (#4540) in `get_action_delay` method. It checks if `config[action]` is `int,float` and if yes it returns default value - so even if we change action delays with `set_action_delays` default value is always returned. I reversed the logic to `is not True` which fixes the bug.
=> Fix get_action_delay method always returning default values #4540

instapy/util.py, tests/test_action_delays.py
Hey,
yesterday's fix of `get_action_delays` method https://github.com/timgrossmann/InstaPy/pull/4606/commits/b71563f7381e48c2bd8cccac1a861f720ddbb452 caused another bug along the line #4610 #4619 #4622 #4610 #4615
`Settings.action_delays` is not initialized properly. As suggested by @lvkins I'm adding another check to see if we have any actions set in `Settings.action_delays`.
Maybe we should initialize `Settings.action_delays` in `__init__` so we have some sensible defaults ?
=> Fix missing check for action and uninitialized action_delays in settings

instapy/instapy.py
When using the functionality set_smart_hashtags with words which are not in English or do not generate more than 9 results for that one hashtag the program will crash with this error:
`Traceback (most recent call last):
File "playing_around_with_quota_supervisor.py", line 58, in <module>
limit=10, sort='random', log_tags=True)
File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 703, in set_smart_hashtags
random_tags = random.sample(data['results'], limit)
File "/usr/lib/python3.7/random.py", line 321, in sample
raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
`
The newly added secure handling will fix this issue for everyone who wants to use the set_smart_hashtags function with sort set to …
=> fix set_smart_hashtags with sort='random'

instapy/like_util.py
Due to a design change at Instagram relating to their structure when searching for pictures by tags the "top_posts" arrays are not being filled anymore (in the whole program probably). Since they are simply returning 0 elements and the top post elements are now being automatically found through the normal image search there wasn't a big error crisis for the users but the like ratio should have gone down drastically for some people since the top post are now being counted as if they were actual posts which could potentially be liked. This would lead to people starting to raise their base values because there are 9 pictures per tag which are definitely not going to get liked.
The quick fix currently works like this: I'm raising the inserted base Amount by 9 to delete the first nine objects …
=> quickfix To Actually Ignore Top Posts when requested

instapy/like_util.py
Error 
TypeError: '<' not supported between instances of 'int' and 'NoneType'
is raised if set     
min_likes=None in set_delimit_liking
=> Fix error `TypeError: '<' not supported between instances of 'int' and 'NoneType'

instapy/util.py
Is there any reason for using `isinstance` to check for which exception? If so please do let me know.
=> Refactor smart_run exceptions handling

instapy/browser.py, instapy/login_util.py
BUG FIXED that prevented the proxy port to be set in firefox + using other API to check for current IP that supports always to return IPv4 
Could be improved further to return IPv6 if the proxy_address given by the user is a IPv6 - but who uses IPv6 ;-)
=> Proxy port fix

DOCUMENTATION.md, instapy/instapy.py, instapy/login_util.py
Issue #5002 : internet connection status = error, when it should not be error
check_browser() function in login_util.py does some checks online that depend on some third party webpages to be available, which does not guarantee the integrity of the results of this check. To my experience this crashes more often than not.
New feature : want_check_browser boolean option at session start, prompts the user a possibility to decide if they want to perform this online check.
=> Fix issue #5002 with new feature

README.md
Quick fix for a broken link in `README.md` for [Pass arguments by CLI](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#pass-arguments-by-cli). It looks like this section was previously included in the file, but has moved over to documentation and can be updated.
=> README.md Link Fix

CHANGELOG.md, DOCUMENTATION.md, instapy/browser.py, instapy/instapy.py
After a fresh install, when I run the standard `quickstart.py` file, I kept getting the exception reported below.
`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`
After some debugging/troubleshooting I found this was due on how the web drivers is initialized and on the fact that the binary path was not part of the specified options so I came up with this fix.
This can also be useful if anyone wants to run InstaPy with a portable version of Firefox.
=> Add the possibility to specify the browser executable path

instapy/util.py, tests/resources/invalid_target_list.txt, tests/resources/valid_target_list.txt, tests/test_file_handling.py
Hello, I found out a mistake I made while implementing the `file_handling` function mentioned on issue #5396 and submitted on pull request #5443. 
I was removing all spaces found before, after and in-between target words and also transforming all letters to lowercase, which would transform a possible comment from `This is a comment` to `thisisacomment`.
I fixed that and updated the unit tests included.
=> Fix text file handling for comments

CHANGELOG.md, instapy/unfollow_util.py
removed and replaced with raw url which already has view-source:
=> duplicate view-source: doesn't allow bot proceed

CHANGELOG.md, instapy/browser.py
This fixes the selenium extension: error problem, for now
Before:  Hide Selenium Extension: error
After: Hide Selenium Extension: ok
=> Add specific agent data to prevent error

CHANGELOG.md, instapy/browser.py
This PR corrects the error "Hide Selenium Extension: Error" mentioned in https://github.com/timgrossmann/InstaPy/issues/5304
=> Correct Hide Selenium Extension: Error

CHANGELOG.md, instapy/xpath_compile.py
Updating XPATH to the like button svg. There's an additional _span_ that's causing the XPATH look up to fail.
=> Fixing XPATH for like svg

CHANGELOG.md, instapy/unfollow_util.py
**THE PROBLEM**
In `unfollow_util.py` a function called `get_following_status` is defined.
In that function the following status is checked with the following code:
```
try:
browser.find_element_by_xpath(
read_xpath(get_following_status.__name__, "follow_button_XP")
)
follow_button_XP = read_xpath(get_following_status.__name__, "follow_button_XP")
except NoSuchElementException:
try:
follow_button = browser.find_element_by_xpath(
read_xpath(get_following_status.__name__, "follow_span_XP_following")
)
return "Following", follow_button
except:
return "UNAVAILABLE", None
```
So if the first `try` block didn't raise exceptions, the status is read from the element and returned at the end of the function:
```
following_status = follow_button.text
return following_status, follow_button
```
The …
=> Fix unfollowing of users that haven't posted anything

CHANGELOG.md, instapy/util.py, instapy/xpath_compile.py
Fix get_links_from_feed xpath expression.
Improve exception handling in click_element(). This doesn't actually fix the root problem of not being able to click the element but at least it prevents the crash that follows an unhandled exception there.
=> like_by_feed() fixes

CHANGELOG.md, instapy/browser.py
Check if resize failed with proxy authentication alert or any other unexpected firefox alert. Now if proxy require login and password UnexpectedAlertPresentException raised and firefox stays open.
=> Processing unexpected alert error on resize

CHANGELOG.md, instapy/browser.py, instapy/instapy.py, instapy/login_util.py, instapy/unfollow_util.py, instapy/util.py
Hello
Here the summary for changes implemented, updated branch to fix/blackify before merge request.
No functionality has been compromised.
1. `login_util.py`
Fixed 80 length for comments; pycodestyle
Comments can be easily adjusted to 80 characters 
2. `unfollow_util.py`
Fixed `except Exception` in line 195
Fixed `edge_type` variable to behave like str(), now it is readable 
3. `util.py`
Fixed 80 length for comments; pycodestyle
Comments can be easily adjusted to 80 characters
4. `browser.py`
Added "from selenium.common.exceptions import UnexpectedAlertPresentException"
due to `except UnexpectedAlertPresentException as exc:` in
`set_selenium_local_session()`
Added `logfolder` parameter in `set_selenium_local_session()` then
geckodriver.log is saved in user/logs instead of src directory …
=> General log rotation, gecko driver log in user directory, comments in 80 chars, 

CHANGELOG.md, instapy/__init__.py
- Use random tag list for `session.like_by_tags`
- General log rotation, gecko driver log in user directory, comments in 80 chars
- Unfollowing of users that haven't posted anything
- `get_links` xpath for yet another change
- Path for Obtaining user id
- `like_util.py` list index out of range error
- `like_by_feed()` method
- `follow_user_following
- processing unexpected alert error on resize
=> Release 6.11

CHANGELOG.md, instapy/unfollow_util.py
Problem: followers_list cleared due to double declaration.
Solution: followers_list is now defined once in `get_users_through_dialog_with_graphql`
ie:
`1605144344786 is 19:25:44.786 GMT-06:00`
```
1605144344786	Marionette	DEBUG	0 <- [1,649,null,{"value":"{\"data\":{\"user\":{\"edge_followed_by\":{\"count\":364124,\"page_info\":{\"has_next_page\":true,\"en ... kS&_nc_tp=25&oh=e5318dac5748263890cb65&oe=5FD5B830\",\"username\":\"dirscejeff\"}}}}]}}},\"status\":\"ok\"}"}]
1605144344787	webdriver::server	DEBUG	<- 200 OK {"value":"{\"data\":{\"user\":{\"edge_followed_by\":{\"count\":364124,\"page_info\":{\"has_next_page\":true,\"end_cursor\":\"QVFEeVM5bWE0dFJ5Nmlqa0taYmFVQU05N21LQVpDRVE1NVkzbDVpTG5hN0R3N1pKNWNPd24TcmNYeg==\"},\"edges\":[{\"node\":{\"id\":\"1999851\",\"username\":
```
```
INFO …
```
=> Subject: fix_5863 followers_list unassigned variable

instapy/xpath_compile.py
it seems that this path is not valid, causing the logic in https://github.com/timgrossmann/InstaPy/blob/master/instapy/comment_util.py#L237 to lead the following test https://github.com/timgrossmann/InstaPy/blob/master/instapy/comment_util.py#L279 to an else statement in https://github.com/timgrossmann/InstaPy/blob/master/instapy/comment_util.py#L305. 
because the unlike button xpath is also incorrect, the program ends up printing this message: https://github.com/timgrossmann/InstaPy/blob/master/instapy/comment_util.py#L314
=> #5895 - possible fix for incorrect xpath used by interact_by_comments

CHANGELOG.md, instapy/login_util.py, instapy/xpath_compile.py
Noticed a typo, it was an extra `s` character. So
changed from `dissmiss_save_information` to `dismiss_save_information`
Nothing else was modified.
CHANGELOG update from #5895
=> Fixed typo in `dissmiss_save_information`  to `dismiss_save_information`

instapy/util.py
There is a small typo in instapy/util.py.
Should read `request` rather than `reqeust`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, reqeust -> request

CHANGELOG.md, instapy/like_util.py
Move call to `get_following_status` above `web_address_navigator` inside
`get_links_for_username` function
This PR fixes the issue #6085, where InstaPy starts interacting with user's posts instead of interacting with tagged posts of the user when using interact_by_users_tagged_posts function.
Fixes #6085
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
- [x ] Test
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] I have checked my code and corrected any misspellings
- [ x] I have performed a self-review of my own code
- [ x] My code follows the style guidelines of this …
=> Fixes issue #6085

.travis.yml, CHANGELOG.md, instapy/login_util.py, requirements.txt
Updated `travis.tml` (format), sorted requirements and versions limits, added `accept_igcookie_dialogue` 
Problem: New IG cookie window in some regions is not handled, that could
induce a crash
Solution: Added second `accept_igcookie_dialogue` to catch the new ID
cookie window
Signed-off-by: elulcao <elulcao@icloud.com>
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
#6060 
Manually, real IG account 
- [ x ] Test
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ NA ] I have made corresponding changes to the documentation
- [ x ] I have checked my code and corrected any misspellings
- [ …
=> Added second `accept_igcookie_dialogue` for new IG cookie page

CHANGELOG.md, instapy/instapy.py
Fixed set_smart_location_hashtags
The old URL of the displaypurposes.com API was obsolete and made the program crash on run
Fixed to the correct URL
Tested and it now works fine
This fix resolves #6094
=> Fix set_smart_location_hashtags

CHANGELOG.md, docs/relationship-tools.md, instapy/instapy.py, instapy/relationship_tools.py
I use this package to pull verified users for my business accounts' followers. This seems to be a common use case, so I figured I'd add these changes to the main repo.
The following command now returns only verified users for username:
```
followers_list = session.grab_followers(username=targetAccount, amount=amount, live_match=True, store_locally=False, verified_only=True)
```
Checked for 5 different accounts, all worked.
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] I have checked my code and corrected any misspellings
- [X ] I have performed a self-review of my own code
- [X ] My code follows the style guidelines of this project, `black -t py34`
- [X ] My changes generate no new warnings
=> Add verified_only flag to get_followers()

CHANGELOG.md, setup.py
switch project_homepage over to https://github.com/InstaPy/InstaPy as the old homepath (https://github.com/timgrossmann/InstaPy) is now a 404
Not tested
=> setup.py - update project_homepage to https://github.com/InstaPy/InstaPy
